#!name=GrandpaNiu CDN Direct Source
#!desc=Image, video, and static CDN protections for fusion module stability

[Rule]
DOMAIN-SUFFIX,alicdn.com,DIRECT,pre-matching
DOMAIN-SUFFIX,aliyuncs.com,DIRECT,pre-matching
DOMAIN-SUFFIX,jdimg.com,DIRECT,pre-matching
DOMAIN-SUFFIX,360buyimg.com,DIRECT,pre-matching
DOMAIN-SUFFIX,pddpic.com,DIRECT,pre-matching
DOMAIN-SUFFIX,pddcdn.com,DIRECT,pre-matching
DOMAIN-SUFFIX,bdimg.com,DIRECT,pre-matching
DOMAIN-SUFFIX,hdslb.com,DIRECT,pre-matching
DOMAIN-SUFFIX,biliimg.com,DIRECT,pre-matching
DOMAIN-SUFFIX,bilivideo.com,DIRECT,pre-matching
DOMAIN-SUFFIX,gtimg.com,DIRECT,pre-matching
DOMAIN-SUFFIX,qpic.cn,DIRECT,pre-matching
