#!name=GrandpaNiu CDN Direct Source
#!desc=Image, video, and static CDN protections for fusion module stability

[Rule]
AND,((DOMAIN-SUFFIX,pddpic.com,extended-matching),(USER-AGENT,"*bili*")),REJECT,pre-matching
AND,((DOMAIN-SUFFIX,pddcdn.com,extended-matching),(USER-AGENT,"*bili*")),REJECT,pre-matching
AND,((DOMAIN-SUFFIX,jdimg.com,extended-matching),(USER-AGENT,"*bili*")),REJECT,pre-matching
AND,((DOMAIN-SUFFIX,360buyimg.com,extended-matching),(USER-AGENT,"*bili*")),REJECT,pre-matching
URL-REGEX,"^https?:\/\/m\.360buyimg\.com\/(?:mobilecms|babel)\/.*",REJECT-IMG,extended-matching
DOMAIN-SUFFIX,alicdn.com,DIRECT,pre-matching
DOMAIN-SUFFIX,aliyuncs.com,DIRECT,pre-matching
DOMAIN-SUFFIX,jdimg.com,DIRECT,pre-matching
DOMAIN-SUFFIX,360buyimg.com,DIRECT,pre-matching
DOMAIN-SUFFIX,bdimg.com,DIRECT,pre-matching
DOMAIN-SUFFIX,hdslb.com,DIRECT,pre-matching
DOMAIN-SUFFIX,biliimg.com,DIRECT,pre-matching
DOMAIN-SUFFIX,bilivideo.com,DIRECT,pre-matching
DOMAIN-SUFFIX,gtimg.com,DIRECT,pre-matching
DOMAIN-SUFFIX,qpic.cn,DIRECT,pre-matching
