#!name=GrandpaNiu Video Protect Source
#!desc=Playback and streaming protection rules

[Rule]
DOMAIN-SUFFIX,bilivideo.com,DIRECT,pre-matching
DOMAIN-SUFFIX,hdslb.com,DIRECT,pre-matching
DOMAIN-SUFFIX,mgtv.com,DIRECT,pre-matching
DOMAIN-SUFFIX,youku.com,DIRECT,pre-matching
