#!name=GrandpaNiu 58汽车 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/part5/58Auto.snippet
# upstream-name: 58汽车
# risk: medium

[Rule]
DOMAIN-SUFFIX,58.xgo.com.cn,REJECT
DOMAIN-SUFFIX,imp.xgo.com.cn,REJECT
