#!name=GrandpaNiu 九游 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partJ/9Game.snippet
# upstream-name: 九游
# risk: medium

[Rule]
DOMAIN-SUFFIX,ad.9game.cn,REJECT
