#!name=GrandpaNiu 阿里云盘 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/AliYunDrive_remove_ads.lpx
# upstream-name: 阿里云盘去广告
# risk: high

[Rule]
IP-CIDR,203.107.1.1/24,REJECT

[URL Rewrite]
^https://member\.alipan\.com/v2/activity/sign_in_luckyBottle - reject-dict
^https://api\.alipan\.com/adrive/v1/file/getTopFolders - reject-dict

[Script]
ali-yun-drive.response.1 = type=http-response,pattern=^https://(biz)?api\.alipan\.com/apps/v\d/users?/home/(news|widgets),requires-body=1,script-path=https://kelee.one/Resource/JavaScript/AliYunDrive/AliYunDrive_remove_ads.js
ali-yun-drive.response.2 = type=http-response,pattern=^https://member\.alipan\.com/v1/users/onboard_list,requires-body=1,script-path=https://kelee.one/Resource/JavaScript/AliYunDrive/AliYunDrive_remove_ads.js

[MITM]
hostname = %APPEND% api.alipan.com,member.alipan.com,bizapi.alipan.com
