#!name=GrandpaNiu AOL Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partA/AOL.snippet
# upstream-name: AOL（美国在线）
# risk: medium

[Rule]
DOMAIN-SUFFIX,adinfo.aol.com,REJECT
DOMAIN-SUFFIX,dynamic.aol.com,REJECT
DOMAIN-SUFFIX,free.aol.com,REJECT
DOMAIN-SUFFIX,mads.aol.com,REJECT
DOMAIN-SUFFIX,cdn.komentary.aol.com,REJECT
