#!name=GrandpaNiu AppSo Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partA/AppSo.snippet
# upstream-name: AppSo
# risk: medium

[URL Rewrite]
^https?://sso\.ifanr\.com/jiong/IOS/appso/splash/ - reject

[MITM]
hostname = %APPEND% sso.ifanr.com
