#!name=GrandpaNiu Bahamut Anime Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/NobyDa/Script/master/Surge/Module/BahamutAnimeAds.sgmodule
# upstream-name: 动画疯
# risk: medium

[Script]
动画疯(屏蔽广告) = type=http-response,pattern=^https:\/\/api\.gamer\.com\.tw(\/mobile_app|)\/anime\/v\d/(token|m3u8|video_src).php\?,requires-body=1,max-size=0,timeout=40,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/Bahamut/BahamutAnimeAds.js

[MITM]
hostname = %APPEND% api.gamer.com.tw
