#!name=GrandpaNiu 百词斩 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partB/baicizhan.snippet
# upstream-name: 百词斩
# risk: medium

[Rule]
DOMAIN,advertise.baicizhan.com,REJECT
DOMAIN,advertise.baicizhan.org,REJECT
