#!name=GrandpaNiu Baidu Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/QingRex/LoonKissSurge/main/Surge/Beta/%E7%99%BE%E5%BA%A6%E7%BD%91%E9%A1%B5%E5%8E%BB%E5%B9%BF%E5%91%8A.beta.sgmodule
# upstream-name: 百度网页去广告
# risk: medium

[Script]
移除百度搜索首页信息流广告 = type=http-response, pattern="^https?:\/\/(www|m)\.baidu\.com\/?($|\?from=\w{8,9})", script-path=https://kelee.one/Resource/JavaScript/BaiduSearch/BaiduSearchHomePage_remove_ads.js, requires-body=true

[MITM]
hostname = %APPEND% m.baidu.com,www.baidu.com
