#!name=GrandpaNiu 一刻相册 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/BaiduPhoto_remove_ads.lpx
# upstream-name: 一刻相册去广告
# risk: medium

[URL Rewrite]
^https://pan\.baidu\.com/act/api/conf\?.*conf_key=youa_core_config_ios - reject-dict
^https://pan\.baidu\.com/youai/material/v1/getbynavid\?.*nav_id=1 - reject-dict

[Body Rewrite]
http-response-jq ^https://mbd\.baidu\.com/ccs/v1/start/confsync\? 'del(.data.service.config.advertisement,.data.service.config.youa.pm_config_ad)'

[MITM]
hostname = %APPEND% pan.baidu.com,mbd.baidu.com
