#!name=GrandpaNiu 半月谈 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partB/BanYueTan.snippet
# upstream-name: 半月谈
# risk: medium

[URL Rewrite]
^https?://www\.banyuetanapp\.com/byt-api/ad/getAdvertList\?adSpaceId=100000002 - reject-200

[MITM]
hostname = %APPEND% www.banyuetanapp.com
