#!name=GrandpaNiu BBC Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partB/BBC.snippet
# upstream-name: BBC
# risk: medium

[Rule]
DOMAIN-SUFFIX,visualscience.external.bbc.co.uk,REJECT
