#!name=GrandpaNiu 笔趣阁 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partB/BiQuGe.snippet
# upstream-name: 笔趣阁
# risk: medium

[Rule]
DOMAIN-SUFFIX,j.biquge520.cc,REJECT
DOMAIN-SUFFIX,m.biquge5200.cc,REJECT
DOMAIN-SUFFIX,tt.biquge.la,REJECT
