#!name=GrandpaNiu 成分喵 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/ChengFenMiao_remove_ads.lpx
# upstream-name: 成分喵去广告
# risk: medium

[URL Rewrite]
^https://app\.chengfenmiao\.com/Listing/LiveHots\? - reject-dict
^https://app\.chengfenmiao\.com/helper/VersionCheck\? - reject-dict
^https://app\.chengfenmiao\.com/item/closet\? - reject-dict
^https://app\.chengfenmiao\.com/Helper/HotWords\? - reject-dict

[Body Rewrite]
http-response-jq ^https://app\.chengfenmiao\.com/helper/setting\? 'del(.detail_buy_sites,.bottom_sites)'

[MITM]
hostname = %APPEND% app.chengfenmiao.com
