#!name=GrandpaNiu 刺猬猫阅读 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partC/CiWeiMaoYueDu.snippet
# upstream-name: 刺猬猫阅读
# risk: medium

[URL Rewrite]
^https?://app\.hbooker\.com/setting/get_startpage_url_list - reject

[MITM]
hostname = %APPEND% app.hbooker.com
