#!name=GrandpaNiu crunchyroll Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partC/Crunchyroll.snippet
# upstream-name: crunchyroll
# risk: medium

[MITM]
hostname = %APPEND% beta-api.crunchyroll.com
