#!name=GrandpaNiu 南网在线 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/CSG_remove_ads.lpx
# upstream-name: 南网在线去广告
# risk: medium

[URL Rewrite]
^https://95598\.csg\.cn/mp/ucs/ma/zt/content/queryHotInformations$ - reject-dict
^https://95598\.csg\.cn/mp/mpaas/rubik/openapi/rubik/mobile/getRubikScene$ - reject-dict

[Body Rewrite]
http-response-jq ^https://95598\.csg\.cn/mp/mpaas/mgw\.htm$ 'if .info | contains("RUBIK-TRACEID:") then .scene.page.areas |= map(select(.areaId | test("kingkong_|9grid_|message_|nearmap_|recommend_"))) else . end'

[MITM]
hostname = %APPEND% 95598.csg.cn
