#!name=GrandpaNiu 推栏 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/Daily_remove_ads.lpx
# upstream-name: 推栏去广告
# risk: medium

[Body Rewrite]
http-response-jq ^https?://m\.pvp\.xoyo\.com/conf/server-mapping$ 'del(.data.splashConf,.data.splashConfNew)'

[MITM]
hostname = %APPEND% m.pvp.xoyo.com
