#!name=GrandpaNiu 大麦 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/Damai_remove_ads.lpx
# upstream-name: 大麦去广告
# risk: medium

[URL Rewrite]
^https://acs\.m\.taobao\.com/gw/mtop\.damai\.wireless\.home\.welcome/ - reject-dict
^https://acs\.m\.taobao\.com/gw/mtop\.damai\.mec\.popup\.get/ - reject-dict

[Body Rewrite]
http-response-jq ^https://acs\.m\.taobao\.com/gw/mtop\.damai\.wireless\.user\.my\.content\.get/ 'del(.data.banner,.data.performFilmVip.userProfitList)'
http-response-jq ^https://acs\.m\.taobao\.com/gw/mtop\.damai\.wireless\.mypage\.feed/ 'del(.data.feedCard)'
http-response-jq ^https://acs\.m\.taobao\.com/gw/mtop\.damai\.mec\.aristotle\.get/ 'del(.data.data.top.keywords)'

[MITM]
hostname = %APPEND% acs.m.taobao.com
