#!name=GrandpaNiu 当当网 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partD/DangDang.snippet
# upstream-name: 当当网
# risk: medium

[Rule]
DOMAIN-SUFFIX,a.dangdang.com,REJECT
DOMAIN-SUFFIX,schprompt.dangdang.com,REJECT
DOMAIN-SUFFIX,t.dangdang.com,REJECT
