#!name=GrandpaNiu 低端影视 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partD/DiDuanYingShi.snippet
# upstream-name: 低端影视
# risk: medium

[URL Rewrite]
^https?://img\.ddrk\.me/ad190824 - reject-img
^https?://img\.ddrk\.me/cover\.png - reject-img
^https?://ddrk\.me/image/logo_footer\.png - reject-img
^https?://ddrk\.me/wp-content/plugins/advanced-floating-content-lite/public/images/close\.png - reject-img

[MITM]
hostname = %APPEND% img.ddrk.me,ddrk.me
