#!name=GrandpaNiu 丁香医生 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partD/DingXiangDoctor.snippet
# upstream-name: 丁香医生
# risk: high

[URL Rewrite]
^https?://dxy\.com/app/i/ask/biz/feed/launch - reject

[MITM]
hostname = %APPEND% dxy.com
