#!name=GrandpaNiu 丁香园 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partD/DingXiangYuan.snippet
# upstream-name: 丁香园
# risk: high

[URL Rewrite]
^https?://dq\.dxy\.cn/api\.php\?action=getpostbanners - reject

[MITM]
hostname = %APPEND% dq.dxy.cn
