#!name=GrandpaNiu DLabel云标签 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partD/DLabelCloudTag.snippet
# upstream-name: DLabel云标签
# risk: medium

[URL Rewrite]
^https://imagepc\.ctaiot\.com/dlabel/0/startpage - reject
^https://dudian-oss\.oss-cn-shenzhen\.aliyuncs\.com/dlabel/1/startpage - reject

[MITM]
hostname = %APPEND% dudian-oss.oss-cn-shenzhen.aliyuncs.com,imagepc.ctaiot.com
