#!name=GrandpaNiu Dlabel云标签 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/Dlabel_remove_ads.lpx
# upstream-name: Dlabel云标签去广告
# risk: medium

[URL Rewrite]
^https://dlabel\.ctaiot\.com/api/spreadstart/list\.json\? - reject-dict
^https://dlabel\.ctaiot\.com/api/spread/journey/select\.json\? - reject-dict

[MITM]
hostname = %APPEND% dlabel.ctaiot.com
