#!name=GrandpaNiu 动画疯 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partD/DongHuaFeng.snippet
# upstream-name: 动画疯
# risk: medium

[URL Rewrite]
^https?://api\.gamer\.com\.tw/mobile_app/anime/v\d/anime_get_question\.php - reject-dict

[Script]
dong-hua-feng.response.14 = type=http-response,pattern=^https?://api\.gamer\.com\.tw/mobile_app/anime/v\d/(token|m3u8).php\?,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/Bahamut/BahamutAnimeAds.js

[MITM]
hostname = %APPEND% api.gamer.com.tw
