#!name=GrandpaNiu 抖音 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partD/TikTok.snippet
# upstream-name: 抖音
# risk: medium

[Rule]
DOMAIN-KEYWORD,p3.pstatp.com,REJECT
