#!name=GrandpaNiu DREAME Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/DREAME_remove_ads.lpx
# upstream-name: DREAME去广告
# risk: medium

[URL Rewrite]
^https://cn\.iot\.dreame\.tech:\d+/dreame-product/public/advertisement/ - reject-dict
^https://cn-mall\.dreame\.tech/dreame-mall/api/v1/tag/list$ - reject-dict
^https://cn-wxmall\.dreame\.tech/main/goods/get-topgoods$ - reject-dict

[Body Rewrite]
http-response-jq ^https://cn\.iot\.dreame\.tech:13267/dreame-system/dreame-app/setting/query$ 'del(.data.appIconConfig)'

[Map Local]
^https://cn\.iot\.dreame\.tech:\d+/dreame-product/public/common-plugin$ data-type=json data="{\"code\":0,\"success\":true,\"data\":{\"version\":1144,\"appVer\":20,\"url\":\"https://kelee.one/Resource/Zip/DREAME/d6996fee95380affdf740ee44a85fbe9___UNI__EDB922E.zip\",\"md5\":\"e0cc9cb77d9e0cf275e41e73dba3f988\",\"validDate\":\"\",\"changeLog\":\"\",\"status\":\"\"},\"msg\":\"操作成功\"}" status-code=200 header="content-type: application/json"

[MITM]
hostname = %APPEND% cn-mall.dreame.tech,cn-wxmall.dreame.tech,cn.iot.dreame.tech
