#!name=GrandpaNiu Facebook Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partF/Facebook.snippet
# upstream-name: Facebook
# risk: medium

[Rule]
DOMAIN-SUFFIX,facebookma.cn,REJECT
DOMAIN-SUFFIX,atdmt.com,REJECT
DOMAIN-SUFFIX,staticxx.facebook.com,REJECT
