#!name=GrandpaNiu Flightradar24 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partF/Flightradar24.snippet
# upstream-name: Flightradar24
# risk: medium

[MITM]
hostname = %APPEND% mobile.flightradar24.com
