#!name=GrandpaNiu 飞客 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/FlyerTea_remove_ads.lpx
# upstream-name: 飞客去广告
# risk: medium

[URL Rewrite]
^https://www\.flyert\.com\.cn/api/mobile/index\.php\?module=advis - reject
^https://www\.flyert\.com\.cn/api/mobile/index\.php\?module=vip_coupon - reject-dict
^https://ptf\.flyertrip\.com/static/img/common/ic_plate_mine_button\.png - reject-img
^https://www\.flyert\.com\.cn/api/mobile/index\.php\?module=getdata - reject-dict

[Script]
flyer-tea.response.1 = type=http-response,pattern=^https://www\.flyert\.com\.cn/api/mobile/index\.php\?version=5,requires-body=1,script-path=https://kelee.one/Resource/JavaScript/FlyerTea/FlyerTea_remove_ads.js
flyer-tea.response.2 = type=http-response,pattern=^https://www\.flyert\.com\.cn/api/mobile/index\.php\?module=plugin&id=k_misign:sign,requires-body=1,script-path=https://kelee.one/Resource/JavaScript/FlyerTea/FlyerTea_remove_ads.js

[MITM]
hostname = %APPEND% www.flyert.com.cn,ptf.flyertrip.com
