#!name=GrandpaNiu 公考雷达 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partG/GongKaoLeiDa.snippet
# upstream-name: 公考雷达
# risk: high

[URL Rewrite]
^https?://api\.gongkaoleida\.com/api/v2/ad/info - reject-dict

[MITM]
hostname = %APPEND% api.gongkaoleida.com
