#!name=GrandpaNiu 好好住 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partH/HaoHaoZhu.snippet
# upstream-name: 好好住
# risk: medium

[URL Rewrite]
^https?://api\.haohaozhu\.cn/index\.php/home/AppInit/getStartPhoto - reject

[MITM]
hostname = %APPEND% api.haohaozhu.cn
