#!name=GrandpaNiu 好游快爆 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partH/HaoYouKuaiBao.snippet
# upstream-name: 好游快爆
# risk: medium

[Rule]
DOMAIN-SUFFIX,ad.3839.com,REJECT
