#!name=GrandpaNiu 和风天气 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partH/HeFengWeather.snippet
# upstream-name: 和风天气
# risk: medium

[URL Rewrite]
^https?://hfapp-service\.qweather\.net/v\d\.\d/app/ad/list\? - reject-dict

[MITM]
hostname = %APPEND% hfapp-service.qweather.net
