#!name=GrandpaNiu 小睡眠 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/HeartideBrainWave_remove_ads.lpx
# upstream-name: 小睡眠去广告
# risk: medium

[URL Rewrite]
^https://api\.psy-1\.com/cosleep/startup\? - reject-dict
^https://api\.psy-1\.com/cosleep/ad/ - reject-dict
^https://api\.psy-1\.com/cosleep/user/identity/ad\? - reject-dict
^https://api\.psy-1\.com/cosleep/discover/ad$ - reject-dict
^https://api\.psy-1\.com/cosleep/home/activity\? - reject-dict
^https://api\.psy-1\.com/cosleep/newborn/ad/ - reject-dict
^https://api\.psy-1\.com/cosleep/my/ad\? - reject-dict
^https://api\.psy-1\.com/cosleep/search/config\? - reject-dict
^https://api\.psy-1\.com/cosleep/newborn/search/ranks\? - reject-dict
^https://api\.psy-1\.com/cosleep/search/inputs\? - reject-dict
^https://api\.psy-1\.com/cosleep/newborn/sleeps/guides/banner\? - reject-dict
^https://api\.psy-1\.com/cosleep/newborn/search/ranks/items\? - reject-dict

[MITM]
hostname = %APPEND% api.psy-1.com
