#!name=GrandpaNiu 火猫 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partH/HuoMao.snippet
# upstream-name: 火猫
# risk: medium

[URL Rewrite]
^https?://api\.huomao\.com/channels/loginAd - reject

[MITM]
hostname = %APPEND% api.huomao.com
