#!name=GrandpaNiu Huya Source
#!desc=App-scoped source fragment for Huya
# source-bootstrap: Release/Ronghemokuai.sgmodule

[Rule]
DOMAIN-SUFFIX,huya.com,DIRECT,pre-matching
DOMAIN-SUFFIX,msstatic.com,DIRECT,pre-matching
DOMAIN,huyafile.msstatic.com,REJECT,pre-matching
DOMAIN,livewebbs2.msstatic.com,REJECT,pre-matching
DOMAIN,livewebbs2pcdn.msstatic.com,REJECT,pre-matching
DOMAIN,pp-cdnfile2pcdn.msstatic.com,REJECT,pre-matching

[MITM]
hostname = %APPEND% *.huya.com,*.msstatic.com
