#!name=GrandpaNiu 小象超市 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/iMaiCai_remove_ads.lpx
# upstream-name: 小象超市去广告
# risk: medium

[URL Rewrite]
^https://mall\.meituan\.com/api/c/homepage/splash - reject-dict
^https://mall\.meituan\.com/api/c/homepage/bubble/operate/info - reject-dict
^https://mall\.meituan\.com/api/c/jigsaw/code/category-banner-\d+/ - reject-dict
^https://mall\.meituan\.com/api/c/poi/\d+/order/recommend/v\d - reject-dict
^https://mall\.meituan\.com/api/c/banner/ - reject-dict
^https://mall\.meituan\.com/api/c/poi/\d+/personal/recommend - reject-dict
^https://businessapi\.ksedt\.com/signupindex/jxlist - reject-dict

[Script]
i-mai-cai.response.1 = type=http-response,pattern=^https://portal-portm\.meituan\.com/horn_ios/mergeRequest,requires-body=1,script-path=https://kelee.one/Resource/JavaScript/iMaiCai/iMaiCai_remove_ads.js

[MITM]
hostname = %APPEND% portal-portm.meituan.com,mall.meituan.com,businessapi.ksedt.com
