#!name=GrandpaNiu 掌阅 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/iReader_remove_ads.lpx
# upstream-name: 掌阅去广告
# risk: medium

[Rule]
DOMAIN,saad.ms.zhangyue.net,REJECT

[URL Rewrite]
^https://(webboot\.zhangyue\.com|ih2\.ireader\.com)/zyapi/bookstore/ad/ - reject-dict
^https://(webboot\.zhangyue\.com|ih2\.ireader\.com)/bookstore/ad/ - reject-dict
^https://(webboot\.zhangyue\.com|ih2\.ireader\.com)/zybk/api/pop/index\? - reject-dict
^https://(webboot\.zhangyue\.com|ih2\.ireader\.com)/zyapi/bookstore/user/mytab\? - reject-dict
^https://(webboot\.zhangyue\.com|ih2\.ireader\.com)/zyboot/activity/mytab\? - reject-dict
https://(webboot\.zhangyue\.com|ih2\.ireader\.com)/zyam/app/app\.php\? - reject-dict

[Body Rewrite]
http-response-jq ^https://(webboot\.zhangyue\.com|ih2\.ireader\.com)/zybook4/iphone/u/p/api\.php\? 'del(.Splash)'
http-response-jq ^https://(webboot\.zhangyue\.com|ih2\.ireader\.com)/bookstore/read/visual/channel/list\? '.body.list |= map(select(.id | contains("ad_") | not))'

[MITM]
hostname = %APPEND% webboot.zhangyue.com,ih2.ireader.com
