#!name=GrandpaNiu JD Source
#!desc=App-scoped source fragment for JD
# source-bootstrap: Release/Ronghemokuai.sgmodule

[Rule]
DOMAIN-SUFFIX,jd.com,DIRECT,pre-matching
DOMAIN-SUFFIX,jd.hk,DIRECT,pre-matching
DOMAIN-SUFFIX,jdcloud.com,DIRECT,pre-matching
DOMAIN-SUFFIX,jdimg.com,DIRECT,pre-matching
DOMAIN-SUFFIX,360buyimg.com,DIRECT,pre-matching
DOMAIN-SUFFIX,360buy.com,DIRECT,pre-matching
DOMAIN-SUFFIX,jdpay.com,DIRECT,pre-matching

[MITM]
hostname = %APPEND% *.jd.com,*.jdimg.com,*.360buyimg.com
