#!name=GrandpaNiu 机核网 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partJ/JiHeWang.snippet
# upstream-name: 机核网
# risk: medium

[URL Rewrite]
^https?://www\.gcores\.com/gapi/v1/app-start-pages\?page - reject-dict

[MITM]
hostname = %APPEND% www.gcores.com
