#!name=GrandpaNiu 简讯 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partJ/JianXun.snippet
# upstream-name: 简讯
# risk: medium

[URL Rewrite]
^https?://api\.tipsoon\.com/api/v1/top/ad - reject-img

[MITM]
hostname = %APPEND% api.tipsoon.com
