#!name=GrandpaNiu 界面新闻 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partJ/JieMianNews.snippet
# upstream-name: 界面新闻
# risk: medium

[URL Rewrite]
^https?://img\.jiemian\.com/ads/ - reject

[MITM]
hostname = %APPEND% img.jiemian.com
