#!name=GrandpaNiu 今日水印相机 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partJ/JinRiShuiYinCamera.snippet
# upstream-name: 今日水印相机
# risk: medium

[URL Rewrite]
^https?://api\.sogaha\.cn/ssp/ad/get\?ip - reject-dict

[MITM]
hostname = %APPEND% api.sogaha.cn
