#!name=GrandpaNiu 看理想 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partK/KanLiXiang.snippet
# upstream-name: 看理想
# risk: medium

[URL Rewrite]
^https?://api\.vistopia\.com\.cn/api/v\d/home/advertisement - reject

[MITM]
hostname = %APPEND% api.vistopia.com.cn
