#!name=GrandpaNiu 看东方（百视TV） Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partK/KanDongFang.snippet
# upstream-name: 看东方（百视TV）
# risk: medium

[URL Rewrite]
^https://bp-api\.bestv\.com\.cn/cms/api/free/open/advertisingV2 - reject-dict

[MITM]
hostname = %APPEND% bp-api.bestv.com.cn,bp-api.bestv.cn
