#!name=GrandpaNiu 口袋校园 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partK/KouDaiXiaoYuan.snippet
# upstream-name: 口袋校园
# risk: high

[URL Rewrite]
^https?://pocketuni\.net/\?app=api&mod=Message&act=ad - reject-200

[MITM]
hostname = %APPEND% pocketuni.net
