#!name=GrandpaNiu 酷6网 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partK/Ku6.snippet
# upstream-name: 酷6网
# risk: medium

[Rule]
DOMAIN-SUFFIX,st.vq.ku6.cn,REJECT
DOMAIN-SUFFIX,addata.ku6.com,REJECT
DOMAIN-SUFFIX,pvdata.ku6.com,REJECT
DOMAIN-SUFFIX,static.ku6.com,REJECT
DOMAIN-SUFFIX,gug.ku6cdn.com,REJECT
DOMAIN-SUFFIX,vi1.ku6img.net,REJECT
DOMAIN-SUFFIX,vi2.ku6img.net,REJECT
