#!name=GrandpaNiu 快压zip Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partK/KuaYaZip.snippet
# upstream-name: 快压zip
# risk: medium

[Rule]
DOMAIN-SUFFIX,kuaizip.com,REJECT
