#!name=GrandpaNiu 快对 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/KuaiDuiZuoYe_remove_ads.lpx
# upstream-name: 快对去广告
# risk: medium

[Rule]
DOMAIN,adx.zuoyebang.com,REJECT

[URL Rewrite]
^https://www\.kuaiduizuoye\.com/init/ad/ - reject-dict
^https://www\.kuaiduizuoye\.com/activity/init/checkappconfig$ - reject-dict
^https://www\.kuaiduizuoye\.com/kdapi/conf/appbannersv3$ - reject-dict
^https://www\.kuaiduizuoye\.com/kdapi/conf/initbanner$ - reject-dict
^https://apivip\.kuaiduizuoye\.com/viponline/scancode/mycard$ - reject-dict

[Body Rewrite]
http-response-jq ^https://www\.kuaiduizuoye\.com/codesearch/aid/home$ 'del(.data.homeBannerList)'

[MITM]
hostname = %APPEND% www.kuaiduizuoye.com,apivip.kuaiduizuoye.com
