#!name=GrandpaNiu 快乐广播 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partK/KuaiLeGuangBo.snippet
# upstream-name: 快乐广播
# risk: medium

[Rule]
DOMAIN,ad.hpplay.cn,REJECT
DOMAIN,adc.hpplay.cn,REJECT
DOMAIN,adcdn.hpplay.cn,REJECT
DOMAIN,adeng.hpplay.cn,REJECT
DOMAIN,pin.hpplay.cn,REJECT
DOMAIN,rp.hpplay.cn,REJECT
DOMAIN,rpt.hpplay.cn,REJECT
