#!name=GrandpaNiu 快懂百科 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partK/KuaiDongBaike.snippet
# upstream-name: 快懂百科
# risk: medium

[Rule]
DOMAIN-SUFFIX,ehd.baike.com,REJECT
DOMAIN-SUFFIX,hdad.baike.com,REJECT
