#!name=GrandpaNiu 快影 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/KwaiVideoeditor_remove_ads.lpx
# upstream-name: 快影去广告
# risk: medium

[URL Rewrite]
^https://api\.kmovie\.gifshow\.com/rest/n/kmovie/app/resource/get\? - reject-dict
^https://api\.kmovie\.gifshow\.com/rest/n/kmovie/app/banner/common/getBannerByType\? - reject-dict
^https://api\.kmovie\.gifshow\.com/rest/n/kmovie/app/merchant/ad/ - reject-dict
^https://api\.kmovie\.gifshow\.com/rest/n/kmovie/app/resource/activity/pendant\? - reject-dict

[Body Rewrite]
http-response-jq ^https://api\.kmovie\.gifshow\.com/rest/n/kmovie/app/banner/common/getBannerByTypeV2\? 'del(.list[] | select(.bannerChannelName == "活动"))'
http-response-jq ^https://api\.kmovie\.gifshow\.com/rest/n/kmovie/app/banner/common/getAllBannerPage\? 'del(.data[] | select(.bannerChannelName == "活动"))'

[MITM]
hostname = %APPEND% api.kmovie.gifshow.com
