#!name=GrandpaNiu 乐播投屏 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partL/LeBoScreenCast.snippet
# upstream-name: 乐播投屏
# risk: medium

[Rule]
DOMAIN-SUFFIX,ad.hpplay.cn,REJECT
DOMAIN-SUFFIX,adeng.hpplay.cn,REJECT
DOMAIN-SUFFIX,rp.hpplay.cn,REJECT
