#!name=GrandpaNiu 乐橙 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partL/LeCheng.snippet
# upstream-name: 乐橙
# risk: high

[URL Rewrite]
^https://dl-cu-hz\.lechange\.cn/oms-online/advertisementPush - reject

[MITM]
hostname = %APPEND% dl-cu-hz.lechange.cn
