#!name=GrandpaNiu 联想至像打印 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partL/LenovoPrint.snippet
# upstream-name: 联想至像打印
# risk: medium

[URL Rewrite]
^https://abcapi\.lenovoimage\.com/v1/promote/startup - reject-dict

[MITM]
hostname = %APPEND% abcapi.lenovoimage.com
