#!name=GrandpaNiu LinkedIn Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partL/LinkedIn.snippet
# upstream-name: LinkedIn
# risk: medium

[Rule]
DOMAIN-SUFFIX,ads.linkedin.com,REJECT
