#!name=GrandpaNiu lofter Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partL/Lofter.snippet
# upstream-name: lofter
# risk: medium

[URL Rewrite]
^https?://ad\.lofter.com/v1\.1/yitou/madr - reject-200
^https?://images\.pinduoduo\.com/marketing\_api - reject-200
^https?://lofter\.lf127\.net/ad\-material - reject-200

[MITM]
hostname = %APPEND% ad.lofter.com,images.pinduoduo.com,lofter.lf127.net
