#!name=GrandpaNiu Lycos Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partL/Lycos.snippet
# upstream-name: Lycos
# risk: medium

[Rule]
DOMAIN-SUFFIX,adbuyer3.lycos.com,REJECT
DOMAIN-SUFFIX,cm8.lycos.com,REJECT
DOMAIN-SUFFIX,oascentral.lycos.com,REJECT
DOMAIN-SUFFIX,ratings.lycos.com,REJECT
DOMAIN-SUFFIX,client.sidesearch.lycos.com,REJECT
DOMAIN-SUFFIX,install.sidesearch.lycos.com,REJECT
DOMAIN-SUFFIX,guestworld.tripod.lycos.com,REJECT
DOMAIN-SUFFIX,titan.guestworld.tripod.lycos.com,REJECT
DOMAIN-SUFFIX,fe.lea.lycos.co.uk,REJECT
DOMAIN-SUFFIX,hit.webcentre.lycos.co.uk,REJECT
