#!name=GrandpaNiu 妈妈网孕育 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partM/MaMaWangYunYu.snippet
# upstream-name: 妈妈网孕育
# risk: high

[URL Rewrite]
^https?://qimg\.cdnmama\.com/rd - reject-dict

[MITM]
hostname = %APPEND% qimg.cdnmama.com
