#!name=GrandpaNiu MacKeeper Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partM/MacKeeper.snippet
# upstream-name: MacKeeper
# risk: medium

[Rule]
DOMAIN-SUFFIX,mackeeper.com,REJECT
DOMAIN-SUFFIX,download.mackeeper.com,REJECT
DOMAIN-SUFFIX,event.mackeeper.com,REJECT
DOMAIN-SUFFIX,mackeeperapp.mackeeper.com,REJECT
DOMAIN-SUFFIX,zryydi.com,REJECT
