#!name=GrandpaNiu 美柚 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/MeetYou_remove_ads.lpx
# upstream-name: 美柚去广告
# risk: medium

[Rule]
DOMAIN,ad.seeyouyima.com,REJECT
DOMAIN,axxd.xmseeyouyima.com,REJECT

[URL Rewrite]
^https://circle\.(xm)?seeyouyima\.com/v\d/article_recommend\? - reject

[Body Rewrite]
http-response-jq ^https://common\.seeyouyima\.com/v2/conf_list$ 'del(.data.confList.Minor_mode_card)'

[MITM]
hostname = %APPEND% circle.seeyouyima.com,circle.xmseeyouyima.com,common.seeyouyima.com
