#!name=GrandpaNiu 每日精选 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partM/MeiRiJingXuan.snippet
# upstream-name: 每日精选
# risk: medium

[URL Rewrite]
http://dili.sqcosmos.com/jiekou/endpage/ad - reject-dict
