#!name=GrandpaNiu 美颜相机 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partM/MeiYanXiangJi.snippet
# upstream-name: 美颜相机
# risk: medium

[Rule]
DOMAIN,adui.tg.meitu.com,REJECT
DOMAIN,aaid.uyunad.com,REJECT
