#!name=GrandpaNiu 美丽修行 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/Meizhixiuxing_remove_ads.lpx
# upstream-name: 美丽修行去广告
# risk: medium

[URL Rewrite]
^https://api\.bevol\.com/appmain/app/home/launch$ - reject-dict
^https://api\.bevol\.com/appmain/app/home/popup$ - reject-dict
^https://api\.bevol\.com/personal/page$ - reject-dict
^https://api\.bevol\.com/seach/foundAndTopSearch$ - reject-dict

[Body Rewrite]
http-response-jq ^https://api\.bevol\.com/appmain/app/home/page$ 'del(.result.versionPopUp,.result.isShowSearchLabel,.result.isShowSearchFeedBack,.result.centerBannerAdvert,.result.programmaticAdvertising,.result.mattsData,.result.questionnaireMap,.result.appPullDownAdvert)'
http-response-jq ^https://api\.bevol\.com/appmain/app/home/feed$ 'del(.result.banners)'
http-response-jq ^https://api\.bevol\.com/appmain/app/home/feed$ '. | .result.returnList |= (map(select(.tname == "userPart"))) | .result.returnList |= map(select(. | has("adId") | not))'
http-response-jq ^https://api\.bevol\.com/trialbox/shop/app/homePage$ 'del(.result.firstPersonActivity,.result.mainActivity,.result.brandZone,.result.imageAD2,.result.couponPopupInfo)'

[MITM]
hostname = %APPEND% api.bevol.com
