#!name=GrandpaNiu 小喵看书 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/MiaoRead_remove_ads.lpx
# upstream-name: 小喵看书去广告
# risk: medium

[URL Rewrite]
^https://api\.miaomiaoyd\.com/book/config/getAdsSettings$ - reject

[MITM]
hostname = %APPEND% api.miaomiaoyd.com
