#!name=GrandpaNiu 漫客栈 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/MKZ_remove_ads.lpx
# upstream-name: 漫客栈去广告
# risk: medium

[URL Rewrite]
^https://base\.mkzcdn\.com/advert/app/read/v\d - reject-dict
^https://base\.mkzcdn\.com/advert/app/story/read/v\d - reject-dict
^https://base\.mkzcdn\.com/advert/app/task/motivate/v\d - reject-dict
^https://base\.mkzcdn\.com/advert/app/user/slide\d/v\d/ - reject-dict

[Script]
mkz.response.1 = type=http-response,pattern=^https://base\.mkzcdn\.com/app/config/,requires-body=1,script-path=https://kelee.one/Resource/JavaScript/MKZ/MKZ_remove_ads.js

[MITM]
hostname = %APPEND% base.mkzcdn.com
