#!name=GrandpaNiu 萌娘百科 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/MoeGirlWiki_remove_ads.lpx
# upstream-name: 萌娘百科去广告
# risk: medium

[URL Rewrite]
^https://grpc\.moegirl\.org\.cn/moegirl\.moepad\.MoepadAppMetaService/GetAppInitialInfo$ - reject
^https://grpc\.moegirl\.org\.cn/moegirl\.moepad\.MoepadService/GetLaunchAdPage$ - reject
^https://grpc\.moegirl\.org\.cn/moegirl\.moepad\.MoepadService/GetFeedAdProbability$ - reject

[MITM]
hostname = %APPEND% grpc.moegirl.org.cn
