#!name=GrandpaNiu 猫扑 (Mop) Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partM/Mop.snippet
# upstream-name: 猫扑 (Mop)
# risk: medium

[Rule]
DOMAIN-SUFFIX,pub.mop.com,REJECT
DOMAIN-SUFFIX,union.mop.com,REJECT
