#!name=GrandpaNiu Naver Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partN/Naver.snippet
# upstream-name: Naver
# risk: medium

[Rule]
DOMAIN-SUFFIX,ad.naver.com,REJECT
DOMAIN-SUFFIX,adcr.naver.com,REJECT
DOMAIN-SUFFIX,adcreative.naver.com,REJECT
DOMAIN-SUFFIX,adimg3.search.naver.net,REJECT
