#!name=GrandpaNiu New Relic Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partN/NewRelic.snippet
# upstream-name: New Relic
# risk: medium

[Rule]
DOMAIN-SUFFIX,newrelic.com,REJECT
DOMAIN-SUFFIX,js-agent.newrelic.com,REJECT
DOMAIN-SUFFIX,bam.nr-data.net,REJECT
