#!name=GrandpaNiu Openmultimedia Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partO/Openmultimedia.snippet
# upstream-name: Openmultimedia
# risk: medium

[Rule]
DOMAIN-SUFFIX,ad.openmultimedia.biz,REJECT
