#!name=GrandpaNiu 向日葵 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/OraySunlogin_remove_ads.lpx
# upstream-name: 向日葵去广告
# risk: medium

[URL Rewrite]
^https://client-api-v2\.oray\.com/materials/SLCC_iOS_DEVICE_FREE\? - reject-dict

[MITM]
hostname = %APPEND% client-api-v2.oray.com
