#!name=GrandpaNiu 开源中国 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partK/OSChina.snippet
# upstream-name: 开源中国
# risk: medium

[URL Rewrite]
^https?://www\.oschina\.net/action/apiv2/get_launcher - reject-img

[MITM]
hostname = %APPEND% www.oschina.net
