#!name=GrandpaNiu Oupeng (欧朋) Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partO/Oupeng.snippet
# upstream-name: Oupeng (欧朋)
# risk: medium

[Rule]
DOMAIN-SUFFIX,ezine.oupeng.com,REJECT
DOMAIN-SUFFIX,img-ad.oupeng.com,REJECT
DOMAIN-SUFFIX,notify.oupeng.com,REJECT
DOMAIN-SUFFIX,startup.oupeng.com,REJECT
DOMAIN-SUFFIX,c.bxb.oupeng.com,REJECT
DOMAIN-SUFFIX,r.bxb.oupeng.com,REJECT
