#!name=GrandpaNiu Outlook Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partO/Outlook.snippet
# upstream-name: Outlook
# risk: medium

[Rule]
DOMAIN,acdn.adnxs.com,REJECT
DOMAIN,mediation.adnxs.com,REJECT
DOMAIN,sin3-ib.adnxs.com,REJECT
