#!name=GrandpaNiu 牛津高阶词典第十版 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partN/OxfordALD10th.snippet
# upstream-name: 牛津高阶词典第十版
# risk: medium

[URL Rewrite]
^https?://oxadmin\.cp\.com\.cn/api/hot/index - reject-dict
^https?://oxadmin\.cp\.com\.cn/api/advertise/banner - reject-dict

[MITM]
hostname = %APPEND% oxadmin.cp.com.cn
