#!name=GrandpaNiu 胖乖生活 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/PangguaiLife_remove_ads.lpx
# upstream-name: 胖乖生活去广告
# risk: medium

[URL Rewrite]
^https://userapi\.qiekj\.com/slot/get$ - reject-dict
^https://userapi\.qiekj\.com/appTitle/get$ - reject-dict
^https://userapi\.qiekj\.com/integralRecord/integralDailStatistics$ - reject-dict
^https://userapi\.qiekj\.com/local-life/category$ - reject-dict
^https://userapi\.qiekj\.com/integralGoods/queryIntegralGoodsPage$ - reject-dict
^https://userapi\.qiekj\.com/task/list$ - reject-dict

[Body Rewrite]
http-response-jq ^https://userapi\.qiekj\.com/local-life/tab-order$ '.data = []'
http-response-jq ^https://userapi\.qiekj\.com/integralGoods/queryIntegralGoodsCategoryList$ '.data = []'

[MITM]
hostname = %APPEND% userapi.qiekj.com
