#!name=GrandpaNiu PCAuto Source
#!desc=App-scoped source fragment for PCAuto and PConline

[Rule]
DOMAIN-SUFFIX,pcauto.com.cn,DIRECT,pre-matching
DOMAIN-SUFFIX,pconline.com.cn,DIRECT,pre-matching
DOMAIN,ad-analysis.pconline.com.cn,REJECT,pre-matching
DOMAIN,iad0ssl.pcauto.com.cn,REJECT,pre-matching
DOMAIN,iad0ssl.pconline.com.cn,REJECT,pre-matching
DOMAIN,imgad0.pcauto.com.cn,REJECT,pre-matching
DOMAIN,imgad0.pconline.com.cn,REJECT,pre-matching

[MITM]
hostname = %APPEND% *.pcauto.com.cn,*.pconline.com.cn
