#!name=GrandpaNiu 皮皮搞笑 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partP/PiPiGaoXiao.snippet
# upstream-name: 皮皮搞笑
# risk: medium

[URL Rewrite]
^https?://adapi\.izuiyou\.com/ad/fetch_api_ads\? - reject-dict

[MITM]
hostname = %APPEND% adapi.izuiyou.com
