#!name=GrandpaNiu 中国人保 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/PICC_Insurance_remove_ads.lpx
# upstream-name: 中国人保去广告
# risk: medium

[URL Rewrite]
^https://zgrb\.epicc\.com\.cn/G-HAPP/h/headlines/queryHeadlines - reject
^https://zgrb\.epicc\.com\.cn/G-HAPP/a/update/startupPage/v1 - reject-dict
^https://zgrb\.epicc\.com\.cn/G-HAPP/a/config/guessYouLike/v3 - reject-dict

[Script]
picc-insurance.response.1 = type=http-response,pattern=^https://zgrb\.epicc\.com\.cn/G-HAPP/a/config/homeInit/v3,requires-body=1,script-path=https://kelee.one/Resource/JavaScript/PICC_Insurance/PICC_Insurance_remove_ads.js

picc-insurance.response.3 = type=http-response,pattern=^https://zgrb\.epicc\.com\.cn/G-HAPP/mpageconfig/myPageConfigList/v3,requires-body=1,script-path=https://kelee.one/Resource/JavaScript/PICC_Insurance/PICC_Insurance_remove_ads.js

[MITM]
hostname = %APPEND% zgrb.epicc.com.cn
