#!name=GrandpaNiu Pinduoduo Source
#!desc=App-scoped source fragment for Pinduoduo
# source-bootstrap: Release/Ronghemokuai.sgmodule

[Rule]
DOMAIN-SUFFIX,pinduoduo.com,DIRECT,pre-matching
DOMAIN-SUFFIX,yangkeduo.com,DIRECT,pre-matching
DOMAIN-SUFFIX,pddpic.com,DIRECT,pre-matching
DOMAIN-SUFFIX,pddcdn.com,DIRECT,pre-matching
DOMAIN,cd-1.pddpic.com,REJECT,pre-matching
DOMAIN,cdl-1.pddpic.com,REJECT,pre-matching
DOMAIN,cdl-p2.pddpic.com,REJECT,pre-matching
DOMAIN,meta.pinduoduo.com,REJECT,pre-matching
DOMAIN,ta-a.pinduoduo.com,REJECT,pre-matching
DOMAIN,ta.pinduoduo.com,REJECT,pre-matching
DOMAIN,th-a.pinduoduo.com,REJECT,pre-matching
DOMAIN,th-b.pinduoduo.com,REJECT,pre-matching
DOMAIN,th.pinduoduo.com,REJECT,pre-matching
DOMAIN,titan.pinduoduo.com,REJECT,pre-matching
DOMAIN,xg.pinduoduo.com,REJECT,pre-matching

[MITM]
hostname = %APPEND% *.pinduoduo.com,*.yangkeduo.com,*.pddpic.com
