#!name=GrandpaNiu 齐鲁网 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partQ/Qilu.snippet
# upstream-name: 齐鲁网
# risk: medium

[Rule]
DOMAIN-SUFFIX,g3.iqilu.com,REJECT
DOMAIN-SUFFIX,g4.iqilu.com,REJECT
