#!name=GrandpaNiu QQ Music Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/QingRex/LoonKissSurge/main/Surge/Beta/QQ%E9%9F%B3%E4%B9%90%E5%8E%BB%E5%B9%BF%E5%91%8A.beta.sgmodule
# upstream-name: QQ音乐去广告
# risk: medium

[Rule]
DOMAIN,adstats.tencentmusic.com,REJECT,extended-matching,pre-matching
DOMAIN,ad.tencentmusic.com,REJECT,extended-matching,pre-matching
DOMAIN,adcdn.tencentmusic.com,REJECT,extended-matching,pre-matching
DOMAIN,adcdn6.tencentmusic.com,REJECT,extended-matching,pre-matching
DOMAIN,adexpo.tencentmusic.com,REJECT,extended-matching,pre-matching
DOMAIN,adclick.tencentmusic.com,REJECT,extended-matching,pre-matching
DOMAIN,mc.tencentmusic.com,REJECT,extended-matching,pre-matching
DOMAIN,monitor.music.qq.com,REJECT,extended-matching,pre-matching
DOMAIN,tmead.y.qq.com,REJECT,extended-matching,pre-matching
DOMAIN,tmeadbak.y.qq.com,REJECT,extended-matching,pre-matching
DOMAIN,tmeadquic.y.qq.com,REJECT,extended-matching,pre-matching
