#!name=GrandpaNiu 全能浏览器 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partQ/QuanNengBrowser.snippet
# upstream-name: 全能浏览器
# risk: medium

[URL Rewrite]
^https?://mi\.gdt\.qq\.com/gdt_mview\.fcg\?posid= - reject-dict

[MITM]
hostname = %APPEND% mi.gdt.qq.com
