#!name=GrandpaNiu 全民K歌 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partQ/QuanMinGeGe.snippet
# upstream-name: 全民K歌
# risk: medium

[URL Rewrite]
^https?://y\.gtimg\.cn/music/common//upload/kg_ad/.+?\d{3,4}x\d{4} - reject-200

[MITM]
hostname = %APPEND% y.gtimg.cn
