#!name=GrandpaNiu ReelShort Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/ReelShort_remove_ads.lpx
# upstream-name: ReelShort去广告
# risk: medium

[URL Rewrite]
^https://(v-api\.crazymaplestudios\.com|d1k8g7qaebqd28\.cloudfront\.net)/api/video/app/getSplashScreenConfig$ - reject-dict
^https://(v-api\.crazymaplestudios\.com|d1k8g7qaebqd28\.cloudfront\.net)/api/video/hall/landingPage$ - reject-dict
^https://(v-api\.crazymaplestudios\.com|d1k8g7qaebqd28\.cloudfront\.net)/api/video/book/getPayModeV2$ - reject-dict

[Body Rewrite]
http-response-jq ^https://(v-api\.crazymaplestudios\.com|d1k8g7qaebqd28\.cloudfront\.net)/api/video/book/getBookDetailV2$ 'del(.data.ad_vip)'
http-response-jq ^https://(v-api\.crazymaplestudios\.com|d1k8g7qaebqd28\.cloudfront\.net)/api/video/hall/infoV3$ 'del(.data.search_keyword_list)'

[MITM]
hostname = %APPEND% v-api.crazymaplestudios.com,d1k8g7qaebqd28.cloudfront.net
