#!name=GrandpaNiu 风鸟 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/RiskBird_remove_ads.lpx
# upstream-name: 风鸟去广告
# risk: medium

[URL Rewrite]
^https://m\.riskbird\.com/prod-qbb-api/user/getBannerList - reject-dict
^https://m\.riskbird\.com/prod-qbb-api/searchHotEnt - reject-dict

[Script]
risk-bird.response.1 = type=http-response,pattern=^https://m\.riskbird\.com/prod-qbb-api/query/person/personRecommend,requires-body=1,script-path=https://kelee.one/Resource/JavaScript/RiskBird/RiskBird_remove_ads.js

[MITM]
hostname = %APPEND% m.riskbird.com
