#!name=GrandpaNiu Roborock Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/Roborock_remove_ads.lpx
# upstream-name: Roborock去广告
# risk: medium

[URL Rewrite]
^https://cniot\.roborock\.com/api/v1/activity/banner/list$ - reject-dict
^https://cniot\.roborock\.com/api/v1/activity/latest$ - reject-dict
^https://cniot\.roborock\.com/api/v1/app/theme/device/icon\? - reject

[Body Rewrite]
http-response-jq ^https://api\.roborock\.com/v2/h5\.page\.item\.info\?id=4115$ '.data |= map(select(.title == "常用功能"))'

[MITM]
hostname = %APPEND% cniot.roborock.com,api.roborock.com
