#!name=GrandpaNiu 萝卜快跑 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/RoboTaxi_remove_ads.lpx
# upstream-name: 萝卜快跑去广告
# risk: medium

[URL Rewrite]
^https://idgdata\.baidu\.com/mc/app/api/listterminal\? - reject-dict
^https://idgdata\.baidu\.com/operation/api/announce/screen/image_manage\? - reject-dict
^https://idgdata\.baidu\.com/idgactivity/api/newuser/info\? - reject-dict

[MITM]
hostname = %APPEND% idgdata.baidu.com
