#!name=GrandpaNiu RQrun Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/RQrun_remove_ads.lpx
# upstream-name: RQrun去广告
# risk: medium

[URL Rewrite]
^https://api\.rq\.run/Api/Spreadimg/spreadimg_type_list$ - reject-dict

[MITM]
hostname = %APPEND% api.rq.run
