#!name=GrandpaNiu 360智慧生活 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/SafetyHome_remove_ads.lpx
# upstream-name: 360智慧生活去广告
# risk: medium

[Rule]
DOMAIN,ad.iot.360.cn,REJECT

[URL Rewrite]
^https://app\.home\.360\.cn/v1/config/custom_config - reject-dict

[MITM]
hostname = %APPEND% app.home.360.cn
