#!name=GrandpaNiu Sape Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partS/Sape.snippet
# upstream-name: Sape
# risk: medium

[Rule]
DOMAIN-SUFFIX,sape.ru,REJECT
DOMAIN-SUFFIX,cdn-rtb.sape.ru,REJECT
DOMAIN-SUFFIX,dispenser-rtb.sape.ru,REJECT
DOMAIN-SUFFIX,ssp-rtb.sape.ru,REJECT
