#!name=GrandpaNiu 剑网三无界 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/SeasunJX3_remove_ads.lpx
# upstream-name: 剑网三无界去广告
# risk: medium

[General]
real-ip=*-update.xoyocdn.com, xg-flow.xoyo.com

[URL Rewrite]
^https://jx3comm\.xoyocdn\.com/jx3gc/zhcn/login_ad/WebCareer/WebCareerTab\.txt - reject

[MITM]
hostname = %APPEND% jx3comm.xoyocdn.com
