#!name=GrandpaNiu 少数派 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partS/ShaoShuPai.snippet
# upstream-name: 少数派
# risk: medium

[URL Rewrite]
https://ios.sspai.com/api/v3/recommend/page/get\?ad.*ios_home_modal - reject

[MITM]
hostname = %APPEND% ios.sspai.com
