#!name=GrandpaNiu 小店掌柜 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/ShopKeeperAdmin_remove_ads.lpx
# upstream-name: 小店掌柜去广告
# risk: medium

[URL Rewrite]
^https://mch\.juhesaas\.com/api/advertisement/ - reject-dict

[MITM]
hostname = %APPEND% mch.juhesaas.com
