#!name=GrandpaNiu 收银通商户端 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/ShouYinTongMerchant_remove_ads.lpx
# upstream-name: 收银通商户端去广告
# risk: high

[URL Rewrite]
^https://syt\.leshuazf\.com/merchant/merchant/showOpenScreenAd$ - reject-dict
^https://m\.fqfin\.cn/cls/leshuapay/preCredit\.json$ - reject-dict
^https://syt\.leshuazf\.com/merchant/messageCenter/stationLetterList$ - reject-dict
^https://syt\.leshuazf\.com/merchant/merchant/getBannerConfig$ - reject-dict
^https://syt\.leshuazf\.com/merchant/popup/getPopupInfo$ - reject-dict

[MITM]
hostname = %APPEND% syt.leshuazf.com,m.fqfin.cn
