#!name=GrandpaNiu 书旗小说 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/ShuQiCenterReader_remove_ads.lpx
# upstream-name: 书旗小说去广告
# risk: medium

[Rule]
DOMAIN,render-web.11222.cn,REJECT

[URL Rewrite]
^https://huichuan\.sm\.cn/nativead - reject-dict
^https://ocean\.shuqireader\.com/api/route/iosReadPage/adV2 - reject-dict
^https://ocean\.shuqireader\.com/api/route/ios/readPage$ - reject-dict
^https://ocean\.shuqireader\.com/api/render/load/resource - reject

[Script]
shu-qi-center-reader.response.1 = type=http-response,pattern=^https://ocean\.shuqireader\.com/sqios/render/render/page/bookstore$,requires-body=1,script-path=https://kelee.one/Resource/JavaScript/ShuQiCenterReader/ShuQiCenterReader_remove_ads.js

[MITM]
hostname = %APPEND% ocean.shuqireader.com,huichuan.sm.cn
