#!name=GrandpaNiu 四季線上影視 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partS/SiJiXianShangYingShi.snippet
# upstream-name: 四季線上影視
# risk: medium

[URL Rewrite]
^https?://service\.4gtv\.tv/4gtv/Data/(?>GetAD|ADLog) - reject-200

[MITM]
hostname = %APPEND% service.4gtv.tv
