#!name=GrandpaNiu 创维 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partC/Skyworth.snippet
# upstream-name: 创维
# risk: medium

[Rule]
DOMAIN-SUFFIX,hoisin.coocaa.com,REJECT
DOMAIN-SUFFIX,hoisin.coocaatv.com,REJECT
DOMAIN,data-hoisin.coocaa.com,REJECT
