#!name=GrandpaNiu B612咔叽 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/SnowCamera_remove_ads.lpx
# upstream-name: B612咔叽去广告
# risk: medium

[Rule]
DOMAIN,api-ad.kajicam.com,REJECT
DOMAIN,zjres-ad.kajicam.com,REJECT
DOMAIN,popup-api.b612kaji.com,REJECT
