#!name=GrandpaNiu 房天下 (Soufun) Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partF/Soufun.snippet
# upstream-name: 房天下 (Soufun)
# risk: medium

[Rule]
DOMAIN-SUFFIX,click1n.soufun.com,REJECT
DOMAIN-SUFFIX,countubn.light.soufun.com,REJECT
