#!name=GrandpaNiu TapTap Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partT/TapTap.snippet
# upstream-name: TapTap
# risk: medium

[URL Rewrite]
^https?://api\.taptapdada\.com/startup-logo/v\d/combo\? - reject-dict

[MITM]
hostname = %APPEND% api.taptapdada.com
