#!name=GrandpaNiu 腾讯体育 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partT/TencentSports.snippet
# upstream-name: 腾讯体育
# risk: high

[URL Rewrite]
^https?://news\.ssp\.qq\.com/app - reject
^https?://sports3\.gtimg\.com/community/20cf93884470434eaf38b2e77ab7796a\.png - reject

[MITM]
hostname = %APPEND% news.ssp.qq.com,sports3.gtimg.com
