#!name=GrandpaNiu 腾讯视频 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/Tencent_Video_remove_ads.lpx
# upstream-name: 腾讯视频去广告
# risk: medium

[Rule]
IP-CIDR,47.110.187.87/32,REJECT

[URL Rewrite]
^https?://vv\.video\.qq\.com/(diff|get)vmind - reject-dict

[Script]
tencent-video.request.1 = type=http-request,pattern=^https?://vv\.video\.qq\.com/getvinfo,requires-body=1,script-path=https://kelee.one/Resource/JavaScript/CommonScript/replace-body.js

[MITM]
hostname = %APPEND% vv.video.qq.com
