#!name=GrandpaNiu 腾讯游戏 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partT/TencentGames.snippet
# upstream-name: 腾讯游戏
# risk: high

[URL Rewrite]
^https?://qt\.qq\.com/lua/mengyou/get_splash_screen_info - reject

[MITM]
hostname = %APPEND% qt.qq.com
