#!name=GrandpaNiu 腾讯游戏社区 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partT/TencentGamesCommunity.snippet
# upstream-name: 腾讯游戏社区
# risk: high

[URL Rewrite]
^https?://static\.gameplus\.qq\.com/img/\d{10}-\d{4}$ - reject

[MITM]
hostname = %APPEND% static.gameplus.qq.com
