#!name=GrandpaNiu 腾讯视频 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/Tencent_Video_remove_ads.lpx
# upstream-name: 腾讯视频去广告
# risk: medium

[Rule]
DOMAIN,adsmind.gdtimg.com,REJECT
DOMAIN,info4.video.qq.com,REJECT
DOMAIN,info6.video.qq.com,REJECT
DOMAIN,ios.video.mpush.qq.com,REJECT
DOMAIN,otheve.beacon.qq.com,REJECT
DOMAIN,pgdt.gtimg.cn,REJECT
DOMAIN,tpns.qq.com,REJECT
DOMAIN,vv6.video.qq.com,REJECT
DOMAIN-SUFFIX,gdt.qq.com,REJECT
DOMAIN-SUFFIX,l.qq.com,REJECT
DOMAIN-KEYWORD,trace.qq.com,REJECT
DOMAIN-KEYWORD,trace.video.qq.com,REJECT
IP-CIDR,47.110.187.87/32,REJECT
URL-REGEX,"^http:\/\/[\d\.:]*\/?(defaultts\.tc|vmind\.qqvideo\.tc|finderpdd\.video)\.qq\.com\/\w+",REJECT
URL-REGEX,"^http:\/\/apd-vlive\.apdcdn\.tc\.qq\.com\/vmind\.qqvideo\.tc\.qq\.com\/\w+",REJECT
URL-REGEX,"^http:\/\/apd-\w+\.v\.smtcdns\.com\/(defaultts|omts|vmind\.qqvideo)\.tc\.qq\.com\/\w+",REJECT

[URL Rewrite]
^https?://vv\.video\.qq\.com/(diff|get)vmind - reject-dict

[Script]
tencent-video.request.1 = type=http-request,pattern=^https?://vv\.video\.qq\.com/getvinfo,requires-body=1,script-path=https://kelee.one/Resource/JavaScript/CommonScript/replace-body.js

[MITM]
hostname = %APPEND% vv.video.qq.com
