#!name=GrandpaNiu TeraBox Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/QingRex/LoonKissSurge/main/Surge/Beta/TeraBox%E5%8E%BB%E5%B9%BF%E5%91%8A.beta.sgmodule
# upstream-name: TeraBox去广告
# risk: high

[Rule]
DOMAIN,ymg-api.terabox.com,REJECT,extended-matching,pre-matching

[Map Local]
^https://www\.terabox\.com/adx/ data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https://www\.terabox\.com/api/ad/ data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https://www\.terabox\.com/api/page/tips\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https://www\.terabox\.com/rest/1\.0/task/common/inttips\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[MITM]
hostname = %APPEND% www.terabox.com
