#!name=GrandpaNiu 天山云TV Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partT/TianShanYunTV.snippet
# upstream-name: 天山云TV
# risk: medium

[URL Rewrite]
^https?://www\.tsytv\.com\.cn/api/app/ios/ads - reject-img

[MITM]
hostname = %APPEND% www.tsytv.com.cn
