#!name=GrandpaNiu TruthSocial Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partT/TruthSocial.snippet
# upstream-name: TruthSocial
# risk: medium

[URL Rewrite]
^https?://truthsocial\.com/api/v\d/truth/ads - reject

[MITM]
hostname = %APPEND% truthsocial.com
