#!name=GrandpaNiu 推栏 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partT/TuiLan.snippet
# upstream-name: 推栏
# risk: medium

[URL Rewrite]
^https?://m\.pvp\.xoyo\.com/conf/server-mapping - reject-dict

[MITM]
hostname = %APPEND% m.pvp.xoyo.com
