#!name=GrandpaNiu Twitch Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/split/partT/Twitch.snippet
# upstream-name: Twitch
# risk: medium

[Rule]
DOMAIN-SUFFIX,fan.twitch.tv,REJECT
DOMAIN-SUFFIX,spade.twitch.tv,REJECT
