#!name=GrandpaNiu 腾讯文档 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/TXDocs_remove_ads.lpx
# upstream-name: 腾讯文档去广告
# risk: medium

[URL Rewrite]
^https://tianshu\.qq\.com/open/ts_access/GetAds\? - reject-dict
^https://h5\.qzone\.qq\.com/p/adboss/api/json/ts_access/GetAds$ - reject-dict

[MITM]
hostname = %APPEND% tianshu.qq.com,h5.qzone.qq.com
