#!name=GrandpaNiu Umetrip Source
#!desc=App-scoped source fragment for Umetrip and flight tools

[Rule]
DOMAIN-SUFFIX,umetrip.com,DIRECT,pre-matching
DOMAIN-SUFFIX,variflight.com,DIRECT,pre-matching
DOMAIN,adv-adlog.variflight.com,REJECT,pre-matching
DOMAIN,sensors.umetrip.com.cn,REJECT,pre-matching

[MITM]
hostname = %APPEND% *.umetrip.com,*.variflight.com
