#!name=GrandpaNiu vgTime Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/app2smile/rules/master/module/vgtime.sgmodule
# upstream-name: vgTimeApp去广告
# risk: medium

[Script]
vgTime = type=http-response,pattern=^http:\/\/app02\.vgtime\.com:8080\/vgtime-app\/api\/v2\/init\/ad\.json,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/vgtime.js
