#!name=GrandpaNiu 挖财记账 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/WaCaiJiZhang_remove_ads.lpx
# upstream-name: 挖财记账去广告
# risk: medium

[URL Rewrite]
^https://jz\.wacaijizhang\.com/api/banners/ribbon\? - reject-dict
^https://jz\.wacaijizhang\.com/api/banners/list\? - reject-dict
^https://jz\.wacaijizhang\.com/api/resource/universal/fetch$ - reject-dict

[MITM]
hostname = %APPEND% jz.wacaijizhang.com
