#!name=GrandpaNiu 微信公众号 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/Weixin_Official_Accounts_remove_ads.lpx
# upstream-name: 微信公众号去广告
# risk: medium

[Rule]
DOMAIN-SUFFIX,wxs.qq.com,REJECT

[URL Rewrite]
^https://mp\.weixin\.qq\.com/mp/(cps_product_info|getappmsgad|jsmonitor|masonryfeed|relatedarticle)\? - reject-dict
^https://mp\.weixin\.qq\.com/mp/relatedsearchword - reject-dict

[MITM]
hostname = %APPEND% mp.weixin.qq.com
