#!name=GrandpaNiu WeChat Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://raw.githubusercontent.com/QingRex/LoonKissSurge/main/Surge/Beta/%E5%BE%AE%E4%BF%A1%E5%85%AC%E4%BC%97%E5%8F%B7%E5%8E%BB%E5%B9%BF%E5%91%8A.beta.sgmodule
# upstream-name: 微信公众号去广告
# risk: high

[Rule]
DOMAIN-SUFFIX,wxs.qq.com,REJECT,extended-matching,pre-matching

[Map Local]
^https://mp\.weixin\.qq\.com/mp/(cps_product_info|getappmsgad|jsmonitor|masonryfeed|relatedarticle)\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https://mp\.weixin\.qq\.com/mp/relatedsearchword data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[MITM]
hostname = %APPEND% mp.weixin.qq.com
