#!name=GrandpaNiu 威锋 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/WPForum_remove_ads.lpx
# upstream-name: 威锋去广告
# risk: medium

[URL Rewrite]
^https://api\.wfdata\.club/v2/yesfeng/yesList\? - reject-dict

[Body Rewrite]
http-response-jq ^https://api\.wfdata\.club/v2/yesfeng/slideshow\? '.data |= map(select(.protocolId == 1))'

[MITM]
hostname = %APPEND% api.wfdata.club
