#!name=GrandpaNiu 磁力宅播放器 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/XFuse_remove_ads.lpx
# upstream-name: 磁力宅播放器去广告
# risk: medium

[URL Rewrite]
^https://cili\.xfuse\.fun/s/ - reject

[MITM]
hostname = %APPEND% cili.xfuse.fun,i.micecube.com,img.mofyi.com
