#!name=GrandpaNiu 小蚕霸王餐 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/XiaoCan_remove_ads.lpx
# upstream-name: 小蚕霸王餐去广告
# risk: medium

[URL Rewrite]
^https://web2\.realtech-inc\.com/oss/xc-app-assets/configs/common/theme\.json - reject-dict
^https://sdk\.1rtb\.net/sdk/req_ad\? - reject-dict
^https://gw\.xiaocantech\.com/g/pa - reject-dict

[Header Rewrite]
http-request ^https://gw\.xiaocantech\.com/rpc header-replace methodname .*(GetBannerList|IsShowOrderAwardPopup|UserLifeShopList|BrandBannerList|GetPromotionGlobalCfg) null

[MITM]
hostname = %APPEND% gw.xiaocantech.com,web2.realtech-inc.com,sdk.1rtb.net
