#!name=GrandpaNiu Xiaopeng Source
#!desc=App-scoped source fragment for Xiaopeng

[Rule]
DOMAIN-SUFFIX,xiaopeng.com,DIRECT,pre-matching
DOMAIN,apps-booster.xiaopeng.com,REJECT,pre-matching
DOMAIN,collect.xiaopeng.com,REJECT,pre-matching

[MITM]
hostname = %APPEND% *.xiaopeng.com
