#!name=GrandpaNiu 小米音箱 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/XiaomiSpeaker_remove_ads.lpx
# upstream-name: 小米音箱去广告
# risk: medium

[URL Rewrite]
^https://marketing-aibox\.v\.mitvos\.com/advertise/ - reject-dict
^https://marketing-aibox\.v\.mitvos\.com/payGuide/halfScreenMulti/(home|cache)\? - reject-dict
^https://marketing-aibox\.v\.mitvos\.com/payGuide/tabPage\? - reject-dict

[MITM]
hostname = %APPEND% marketing-aibox.v.mitvos.com
