#!name=GrandpaNiu 小黑盒 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/XiaoHeiHe_remove_ads.lpx
# upstream-name: 小黑盒去广告
# risk: medium

[URL Rewrite]
^https://api\.xiaoheihe\.cn/account/get_ads_info_v2 - reject-dict

[Body Rewrite]
http-response-jq ^https://api\.xiaoheihe\.cn/bbs/app/feeds/news '.result.links |= map(if .content_type == 27 then del(.title, .ad_pm, .img_gif, .idea_id, .ad_report, .label, .source, .intranet_only, .ad_cm, .content_type, .PROTOCOL, .img, .ad_ratio) else . end)'

[MITM]
hostname = %APPEND% api.xiaoheihe.cn
