#!name=GrandpaNiu Yiche Source
#!desc=App-scoped source fragment for Yiche

[Rule]
DOMAIN-SUFFIX,yiche.com,DIRECT,pre-matching
DOMAIN,adx.yiche.com,REJECT,pre-matching
DOMAIN,log.ycapp.yiche.com,REJECT,pre-matching

[MITM]
hostname = %APPEND% *.yiche.com
