#!name=GrandpaNiu 有道云笔记 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/YoudaoNote_remove_ads.lpx
# upstream-name: 有道云笔记去广告
# risk: medium

[URL Rewrite]
^https://silk\.lx\.netease\.com/api/open/advertOpen/ - reject-dict

[MITM]
hostname = %APPEND% silk.lx.netease.com
