#!name=GrandpaNiu Youku Source
#!desc=App-scoped source fragment for Youku

[Rule]
DOMAIN-SUFFIX,youku.com,DIRECT,pre-matching
DOMAIN,push.m.youku.com,DIRECT
DOMAIN,un-acs.youku.com,DIRECT
DOMAIN,et.ykccn.com,REJECT,pre-matching

[MITM]
hostname = %APPEND% *.youku.com,*.ykccn.com
