#!name=GrandpaNiu YouTube Source
#!desc=App-scoped source fragment for YouTube
# source-bootstrap: Release/Modules/youtube.sgmodule

[Rule]
AND,((DOMAIN-SUFFIX,googlevideo.com), (PROTOCOL,UDP)),REJECT
AND,((DOMAIN), (PROTOCOL,UDP)),REJECT

[Map Local]

[Script]

