#!name=GrandpaNiu YY语音 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/YYVoiceTool_remove_ads.lpx
# upstream-name: YY语音去广告
# risk: medium

[URL Rewrite]
^https://yuyin-api\.baizhanlive\.com/homepage/flashscreen/get\? - reject-dict
^https://yuyin-api\.baizhanlive\.com/homepage/homepage/banner\? - reject-dict
^https://web\.yy\.com/yyvoice_task_sys/bar\.html\? - reject
^https://yuyin-api\.baizhanlive\.com/search/search/hotword\? - reject-dict

[Body Rewrite]
http-response-jq ^https://yuyin-api\.baizhanlive\.com/postsquare/college/page/tabsV3\? '.data.tabList |= map(select(.code == "post" or .code == "teamup" or .code == "college" or .code == "aiSecretRoom"))'

[MITM]
hostname = %APPEND% yuyin-api.baizhanlive.com,web.yy.com
