#!name=GrandpaNiu 智联招聘 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/ZhiLianZhaoPin_remove_ads.lpx
# upstream-name: 智联招聘去广告
# risk: medium

[Rule]
URL-REGEX,"^https:\/\/(ask|cgate)\.zhaopin\.com\/operation\/ad\/",REJECT

[URL Rewrite]
^https://cgate\.zhaopin\.com/resumeapi/resumeCheck/positionDetailBottomTipCheck$ - reject-dict
^https://cgate\.zhaopin\.com/bdp/commercial/queryLinkData$ - reject

[Body Rewrite]
http-response-jq ^https://ask\.zhaopin\.com/plat-zqa-server/home/\d\.\d\.\d/getHomeContents\? 'del(.data.templates[0].data.banner)'

[MITM]
hostname = %APPEND% ask.zhaopin.com,cgate.zhaopin.com
