#!name=GrandpaNiu 纵横小说 Source
#!desc=Auto-synced app-scoped source fragment
# auto-sync: true
# source-url: https://kelee.one/Tool/Loon/Lpx/ZongHeng_remove_ads.lpx
# upstream-name: 纵横小说去广告
# risk: medium

[URL Rewrite]
^https://api1\.zongheng\.com/iosapi/system/startup$ - reject
^https://api2\.zongheng\.com/api/giftBag/bindingBag$ - reject-dict

[MITM]
hostname = %APPEND% api?.zongheng.com
