#!/usr/bin/env python3
"""Build a web-facing release catalog for GrandpaNiu.

The catalog is a lightweight distribution index. It does not replace existing
root HTML pages. It adds structured links under Web/ so users can find the
current module, rule, app module, and Android release entries from one place.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WEB_DIR = ROOT / "Web"
MODULES_README = ROOT / "Release" / "Modules" / "README.md"
CATALOG_MD = WEB_DIR / "catalog.md"
CATALOG_JSON = WEB_DIR / "release-links.json"
BASE = "https://grandpaniuu.github.io/GrandpaNiu"
RAW = "https://raw.githubusercontent.com/GrandpaNiuu/GrandpaNiu/main"

CORE_LINKS = [
    ("Fusion module", "Ronghemokuai.sgmodule", f"{RAW}/Ronghemokuai.sgmodule"),
    ("Release module", "Release/Ronghemokuai.sgmodule", f"{RAW}/Release/Ronghemokuai.sgmodule"),
    ("Rules", "Release/Rules.conf", f"{RAW}/Release/Rules.conf"),
    ("Rule groups", "Release/RulesGroup.conf", f"{RAW}/Release/RulesGroup.conf"),
    ("Web import page", "import.html", f"{BASE}/import.html"),
    ("Android import page", "android.html", f"{BASE}/android.html"),
]

ANDROID_LINKS = [
    ("Mihomo", "Release/Android/mihomo/"),
    ("sing-box", "Release/Android/sing-box/"),
    ("AdGuard", "Release/Android/adguard/"),
    ("v2rayNG", "Release/Android/v2rayng/"),
]


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace") if path.exists() else ""


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.rstrip() + "\n", encoding="utf-8", newline="\n")


def parse_modules() -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for line in read(MODULES_README).splitlines():
        if not line.startswith("| GrandpaNiu"):
            continue
        parts = [part.strip() for part in line.strip("|").split("|")]
        if len(parts) < 4:
            continue
        name = parts[0]
        file_name = parts[1].strip("`")
        source = parts[2].strip("`")
        sections = parts[3]
        rows.append({
            "name": name,
            "file": f"Release/Modules/{file_name}",
            "source": source,
            "sections": sections,
            "raw_url": f"{RAW}/Release/Modules/{file_name}",
        })
    return rows


def build_json(modules: list[dict[str, str]]) -> str:
    payload = {
        "name": "GrandpaNiu release catalog",
        "base_url": BASE,
        "raw_base_url": RAW,
        "core": [
            {"name": name, "path": path, "url": url}
            for name, path, url in CORE_LINKS
        ],
        "modules": modules,
        "android": [
            {"name": name, "path": path, "url": f"{RAW}/{path}"}
            for name, path in ANDROID_LINKS
        ],
    }
    return json.dumps(payload, ensure_ascii=False, indent=2)


def build_md(modules: list[dict[str, str]]) -> str:
    lines = [
        "# GrandpaNiu Release Catalog",
        "",
        "This catalog collects the public release links generated by the module factory.",
        "",
        "## Core links",
        "",
        "| Name | Path | URL |",
        "|---|---|---|",
    ]
    for name, path, url in CORE_LINKS:
        lines.append(f"| {name} | `{path}` | {url} |")
    lines.extend([
        "",
        "## App modules",
        "",
        "| Module | File | Source | Sections | URL |",
        "|---|---|---|---|---|",
    ])
    for item in modules:
        lines.append(f"| {item['name']} | `{item['file']}` | `{item['source']}` | {item['sections']} | {item['raw_url']} |")
    lines.extend([
        "",
        "## Android release directories",
        "",
        "| Format | Path | URL |",
        "|---|---|---|",
    ])
    for name, path in ANDROID_LINKS:
        lines.append(f"| {name} | `{path}` | {RAW}/{path} |")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    modules = parse_modules()
    write(CATALOG_JSON, build_json(modules))
    write(CATALOG_MD, build_md(modules))
    print(f"Built {CATALOG_MD} and {CATALOG_JSON}")


if __name__ == "__main__":
    main()
