#!/usr/bin/env python3
"""Build web-facing catalogs for release and remote source governance."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WEB_DIR = ROOT / "Web"
REMOTES_DIR = ROOT / "Rewrite" / "Remotes"
MODULES_README = ROOT / "Release" / "Modules" / "README.md"
SOURCES_JSON = REMOTES_DIR / "sources.json"
CATALOG_MD = WEB_DIR / "catalog.md"
CATALOG_JSON = WEB_DIR / "release-links.json"
REMOTES_WEB_MD = WEB_DIR / "remotes.md"
REMOTES_CATALOG_MD = REMOTES_DIR / "Catalog.md"
BASE = "https://grandpaniuu.github.io/GrandpaNiu"
RAW = "https://raw.githubusercontent.com/GrandpaNiuu/GrandpaNiu/main"

CORE_LINKS = [
    ("GitHub Pages home", "Web/index.html", f"{BASE}/Web/index.html"),
    ("Fusion module", "Ronghemokuai.sgmodule", f"{RAW}/Ronghemokuai.sgmodule"),
    ("Release module", "Release/Ronghemokuai.sgmodule", f"{RAW}/Release/Ronghemokuai.sgmodule"),
    ("Release module alias", "Release/Module.sgmodule", f"{RAW}/Release/Module.sgmodule"),
    ("Rules", "Release/Rules.conf", f"{RAW}/Release/Rules.conf"),
    ("Rule groups", "Release/RulesGroup.conf", f"{RAW}/Release/RulesGroup.conf"),
    ("Web import page", "import.html", f"{BASE}/import.html"),
    ("Android import page", "android.html", f"{BASE}/android.html"),
]

ANDROID_LINKS = [
    ("Mihomo", "Release/Android/mihomo/"),
    ("sing-box", "Release/Android/sing-box/"),
    ("AdGuard", "Release/Android/adguard/"),
    ("v2rayNG", "Release/Android/v2rayng/"),
]

WINDOWS_LINKS = [
    ("v2rayN custom routing", "Windows/v2rayN/GrandpaNiu-v2rayN-custom-routing.json"),
    ("v2rayN README", "Windows/v2rayN/README.md"),
]
CAPABILITY_CONTRACT = "Static section depth only; does not certify runtime effectiveness or device compatibility."


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace") if path.exists() else ""


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.rstrip() + "\n", encoding="utf-8", newline="\n")


def parse_module_row(line: str) -> dict[str, str] | None:
    if not line.startswith("| GrandpaNiu"):
        return None
    parts = [part.strip() for part in line.strip("|").split("|")]
    if len(parts) == 4:
        name, raw_file, raw_source, sections = parts
        capability = "unclassified"
    elif len(parts) >= 5:
        name, raw_file, raw_source, capability, sections = parts[:5]
    else:
        return None
    file_name = raw_file.strip("`")
    return {
        "name": name,
        "file": f"Release/Modules/{file_name}",
        "source": raw_source.strip("`"),
        "capability": capability,
        "sections": sections,
        "raw_url": f"{RAW}/Release/Modules/{file_name}",
    }


def parse_modules() -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for line in read(MODULES_README).splitlines():
        item = parse_module_row(line)
        if item is not None:
            rows.append(item)
    return rows


def parse_remotes() -> dict[str, list[dict[str, object]]]:
    try:
        data = json.loads(read(SOURCES_JSON) or "{}")
    except json.JSONDecodeError:
        return {"rule_sets": [], "reference_modules": []}
    return {
        "rule_sets": list(data.get("rule_sets", [])),
        "reference_modules": list(data.get("reference_modules", [])),
    }


def remote_summary(remotes: dict[str, list[dict[str, object]]]) -> dict[str, int]:
    rule_sets = remotes["rule_sets"]
    refs = remotes["reference_modules"]
    return {
        "rule_sets": len(rule_sets),
        "enabled_rule_sets": sum(1 for item in rule_sets if item.get("enabled") is True),
        "protected_rule_sets": sum(1 for item in rule_sets if item.get("protected") is True),
        "reference_modules": len(refs),
        "enabled_reference_modules": sum(1 for item in refs if item.get("enabled") is True),
        "protected_reference_modules": sum(1 for item in refs if item.get("protected") is True),
    }


def build_json(modules: list[dict[str, str]], remotes: dict[str, list[dict[str, object]]]) -> str:
    payload = {
        "name": "GrandpaNiu release catalog",
        "base_url": BASE,
        "raw_base_url": RAW,
        "capability_contract": CAPABILITY_CONTRACT,
        "core": [{"name": name, "path": path, "url": url} for name, path, url in CORE_LINKS],
        "modules": modules,
        "android": [{"name": name, "path": path, "url": f"{RAW}/{path}"} for name, path in ANDROID_LINKS],
        "windows": [{"name": name, "path": path, "url": f"{RAW}/{path}"} for name, path in WINDOWS_LINKS],
        "remotes": remote_summary(remotes),
    }
    return json.dumps(payload, ensure_ascii=False, indent=2)


def build_md(modules: list[dict[str, str]]) -> str:
    lines = [
        "# GrandpaNiu Release Catalog",
        "",
        "This catalog collects the public release links generated by the module factory.",
        "",
        "## Build status",
        "",
        "[![Module Factory Build](https://github.com/GrandpaNiuu/GrandpaNiu/actions/workflows/module-factory-build.yml/badge.svg)](https://github.com/GrandpaNiuu/GrandpaNiu/actions/workflows/module-factory-build.yml)",
        "[![Repository Health Check](https://github.com/GrandpaNiuu/GrandpaNiu/actions/workflows/repository-health.yml/badge.svg)](https://github.com/GrandpaNiuu/GrandpaNiu/actions/workflows/repository-health.yml)",
        "[![Scheduled Module Update](https://github.com/GrandpaNiuu/GrandpaNiu/actions/workflows/scheduled-module-update.yml/badge.svg)](https://github.com/GrandpaNiuu/GrandpaNiu/actions/workflows/scheduled-module-update.yml)",
        "",
        "## Core links",
        "",
        "| Name | Path | URL |",
        "|---|---|---|",
    ]
    for name, path, url in CORE_LINKS:
        lines.append(f"| {name} | `{path}` | {url} |")
    lines.extend([
        "",
        "## App modules",
        "",
        CAPABILITY_CONTRACT,
        "",
        "| Module | File | Source | Capability | Sections | URL |",
        "|---|---|---|---|---|---|",
    ])
    for item in modules:
        lines.append(
            f"| {item['name']} | `{item['file']}` | `{item['source']}` | "
            f"{item['capability']} | {item['sections']} | {item['raw_url']} |"
        )
    lines.extend(["", "## Android release directories", "", "| Format | Path | URL |", "|---|---|---|"])
    for name, path in ANDROID_LINKS:
        lines.append(f"| {name} | `{path}` | {RAW}/{path} |")
    lines.extend(["", "## Windows release files", "", "| Format | Path | URL |", "|---|---|---|"])
    for name, path in WINDOWS_LINKS:
        lines.append(f"| {name} | `{path}` | {RAW}/{path} |")
    lines.extend(["", "## Remote governance", "", "See `Web/remotes.md` and `Rewrite/Remotes/Catalog.md`.", ""])
    return "\n".join(lines)


def build_remotes_md(remotes: dict[str, list[dict[str, object]]], target: str) -> str:
    summary = remote_summary(remotes)
    lines = [
        "# Remote Source Catalog",
        "",
        f"Target: {target}",
        "",
        "## Summary",
        "",
        f"- Rule sets: {summary['rule_sets']}",
        f"- Enabled rule sets: {summary['enabled_rule_sets']}",
        f"- Protected rule sets: {summary['protected_rule_sets']}",
        f"- Reference modules: {summary['reference_modules']}",
        f"- Enabled reference modules: {summary['enabled_reference_modules']}",
        f"- Protected reference modules: {summary['protected_reference_modules']}",
        "",
        "## Active rule sets",
        "",
        "| Name | Type | Policy | Protected | Purpose | URL |",
        "|---|---|---|---|---|---|",
    ]
    for item in remotes["rule_sets"]:
        if item.get("enabled") is not True:
            continue
        lines.append(f"| {item.get('name', '')} | {item.get('type', '')} | {item.get('policy', '')} | {item.get('protected', False)} | {item.get('purpose', '')} | {item.get('url', '')} |")
    lines.extend(["", "## Reference modules", "", "| Name | Enabled | Protected | Purpose | URL |", "|---|---:|---:|---|---|"])
    for item in remotes["reference_modules"]:
        lines.append(f"| {item.get('name', '')} | {item.get('enabled', False)} | {item.get('protected', False)} | {item.get('purpose', '')} | {item.get('url', '')} |")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    modules = parse_modules()
    remotes = parse_remotes()
    write(CATALOG_JSON, build_json(modules, remotes))
    write(CATALOG_MD, build_md(modules))
    write(REMOTES_WEB_MD, build_remotes_md(remotes, "Web distribution"))
    write(REMOTES_CATALOG_MD, build_remotes_md(remotes, "Rewrite remote governance"))
    print(f"Built {CATALOG_MD}, {CATALOG_JSON}, {REMOTES_WEB_MD}, and {REMOTES_CATALOG_MD}")


if __name__ == "__main__":
    main()
