# Spotify upstream script (Kelee)
spotify-upstream = type=http-response,pattern=^https://(?:\w+-spclient|spclient\.wg)\.spotify\.com(?::443)?/(?:bootstrap|user-customization-service),requires-body=1,binary-body-mode=1,script-path=https://kelee.one/Resource/JavaScript/Spotify/Spotify_remove_ads.js,timeout=5
