#!/usr/bin/env python3
"""Unified repository validator for the single fusion module factory."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parents[1]
MODULE = ROOT / "Ronghemokuai.sgmodule"
RELEASE = ROOT / "Release" / "Ronghemokuai.sgmodule"
SOURCES_JSON = ROOT / "Rewrite" / "Remotes" / "sources.json"
CANDIDATES_JSON = ROOT / "Rewrite" / "Remotes" / "candidates.json"
README = ROOT / "README.md"
EXPECTED_UPDATE_URL = "#!update-url=https://grandpaniuu.github.io/GrandpaNiu/Ronghemokuai.sgmodule"
REQUIRED_MARKERS = (
    "[Rule]",
    "[URL Rewrite]",
    "[Header Rewrite]",
    "[Body Rewrite]",
    "[Map Local]",
    "[Script]",
    "[MITM]",
    "spotify-json",
    "spotify-proto",
    "youtube.response",
    "zhihu-enhance",
    EXPECTED_UPDATE_URL,
)
SPOTIFY_HEADER_REWRITE_RULE = r"http-request ^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/user-customization-service\/v1\/customize$ header-del if-none-match"
SPOTIFY_SCRIPT_MARKERS = ("spotify-json", "spotify-proto")
SPOTIFY_MITM_HOSTS = ("spclient.wg.spotify.com", "*.spclient.spotify.com")
REQUIRED_GOVERNANCE_FILES = (
    "SECURITY.md",
    "LICENSE",
    "CONTRIBUTING.md",
    "docs/SCRIPT_REVIEW.md",
    "docs/MITM_POLICY.md",
    "docs/VERSIONING.md",
    "docs/ROADMAP.md",
    "docs/PROFILE_POLICY.md",
    "scripts/build_release_variants.py",
    "scripts/audit_reject_risk.py",
    "scripts/generate_app_status_matrix.py",
    "scripts/create_promotion_pr.py",
    "scripts/score_candidates.py",
    "scripts/check_report_freshness.py",
    "scripts/audit_domestic_app_connectivity.py",
    "reports/multi_release_report.md",
    "reports/reject_risk_report.md",
    "reports/app_status_matrix.md",
    "reports/promotion_pr_report.md",
    "reports/candidate_security_score_report.md",
    "reports/report_freshness_report.md",
    "reports/domestic_app_connectivity_audit.md",
    "Rewrite/Profiles/fusion.conf",
    "Rewrite/Sources/MITM-core.conf",
    "Rewrite/Sources/MITM-app-clean.conf",
    "Rewrite/Sources/MITM-stable-plus.conf",
    "Rewrite/Sources/MITM-extended.conf",
    "backup/manifest.json",
)
REQUIRED_WORKFLOWS = (
    ".github/workflows/module-factory-build.yml",
    ".github/workflows/daily-module-update.yml",
    ".github/workflows/daily-invalid-source-repair.yml",
    ".github/workflows/upstream-collect.yml",
    ".github/workflows/repository-health.yml",
)
ALLOWED_REMOTE_TYPES = {"RULE-SET", "DOMAIN-SET"}
ALLOWED_POLICIES = {"REJECT", "REJECT-DROP", "DIRECT"}
BLOCKED_URL_TOKENS = ("ghproxy", "mirror", "tinyurl", "bit.ly", "t.co/", "shorturl")
RISK_TOKENS = (
    "GPT",
    "ChatGPT",
    "OpenAI",
    "generated by AI",
    ".claude",
    "CLAUDE.md",
)
SCRIPT_NAME_RE = re.compile(r"^\s*([^#\s][^=]+?)\s*=")
HOSTNAME_RE = re.compile(r"^\s*hostname\s*=\s*(.+)$")
MD_LINK_RE = re.compile(r"\[[^\]]+\]\(([^)]+)\)")
ZH_FILTER_PATTERN = re.compile(r"(topstory|moments|feed|questions|answers|search|commercial|market|ad|recommend)", re.I)


def fail(message: str) -> None:
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(1)


def read_text(path: Path) -> str:
    if not path.exists():
        fail(f"missing file: {path.relative_to(ROOT)}")
    return path.read_text(encoding="utf-8", errors="replace")


def read_json(path: Path) -> dict:
    try:
        return json.loads(read_text(path))
    except json.JSONDecodeError as exc:
        fail(f"invalid JSON in {path.relative_to(ROOT)}: {exc}")


def active_lines(text: str) -> Iterable[str]:
    for line in text.splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            yield stripped


def parse_hosts(text: str) -> list[str]:
    hosts: list[str] = []
    for line in text.splitlines():
        match = HOSTNAME_RE.match(line)
        if not match:
            continue
        value = match.group(1).replace("%APPEND%", "")
        for host in value.split(","):
            clean = host.strip()
            if clean:
                hosts.append(clean)
    return hosts


def validate_root_release() -> None:
    root_text = read_text(MODULE)
    release_text = read_text(RELEASE)
    if root_text != release_text:
        fail("Ronghemokuai.sgmodule and Release/Ronghemokuai.sgmodule differ")
    for marker in REQUIRED_MARKERS:
        if marker not in root_text:
            fail(f"required marker missing from root module: {marker}")


def validate_single_release_report() -> None:
    report = read_text(ROOT / "reports" / "multi_release_report.md")
    if "单一融合版发布报告" not in report:
        fail("multi_release_report.md must describe the single fusion release")
    if "Ronghemokuai.sgmodule" not in report or "fusion" not in report:
        fail("multi_release_report.md missing fusion release entry")


def validate_remote_schema() -> None:
    data = read_json(SOURCES_JSON)
    urls: set[str] = set()
    for index, item in enumerate(data.get("rule_sets", []), 1):
        for key in ("name", "type", "url", "policy", "enabled", "protected", "purpose"):
            if key not in item:
                fail(f"sources.json rule_sets[{index}] missing {key}")
        if item["type"] not in ALLOWED_REMOTE_TYPES:
            fail(f"sources.json rule_sets[{index}] invalid type: {item['type']}")
        if item["policy"] not in ALLOWED_POLICIES:
            fail(f"sources.json rule_sets[{index}] invalid policy: {item['policy']}")
        url = str(item["url"])
        if not url.startswith("https://"):
            fail(f"sources.json rule_sets[{index}] must use https: {url}")
        if any(token in url.lower() for token in BLOCKED_URL_TOKENS):
            fail(f"sources.json rule_sets[{index}] uses blocked host/token: {url}")
        if url in urls:
            fail(f"duplicate remote source url in sources.json: {url}")
        urls.add(url)

    candidates = read_json(CANDIDATES_JSON)
    if candidates.get("policy", {}).get("search_web") is not False:
        fail("candidates.json policy.search_web must stay false")
    trusted = candidates.get("trusted_repositories", [])
    if not isinstance(trusted, list) or not trusted:
        fail("candidates.json must define trusted_repositories")


def validate_scripts() -> None:
    spotify_text = read_text(ROOT / "Scripts" / "spotify.conf")
    youtube_text = read_text(ROOT / "Scripts" / "youtube.conf")
    app_text = read_text(ROOT / "Scripts" / "app-clean.conf")

    if "spotify-json" not in spotify_text or "spotify-proto" not in spotify_text:
        fail("Scripts/spotify.conf must contain spotify-json and spotify-proto")
    if "youtube.response" not in youtube_text:
        fail("Scripts/youtube.conf must contain youtube.response")
    if not any(token in app_text.lower() for token in ("tieba", "qq-news", "vgtime", "fmz200", "zirawell", "wool_scripts", "app2smile")):
        fail("Scripts/app-clean.conf does not appear to contain app cleanup scripts")

    names: set[str] = set()
    for path in (ROOT / "Scripts").glob("*.conf"):
        for line in active_lines(read_text(path)):
            match = SCRIPT_NAME_RE.match(line)
            if not match:
                continue
            name = match.group(1).strip()
            if name in names:
                fail(f"duplicate script name: {name}")
            names.add(name)


def validate_spotify_integration() -> None:
    header_text = read_text(ROOT / "Rewrite" / "Sources" / "Header-Rewrite.conf")
    spotify_text = read_text(ROOT / "Scripts" / "spotify.conf")
    mitm_core_text = read_text(ROOT / "Rewrite" / "Sources" / "MITM-core.conf")

    if SPOTIFY_HEADER_REWRITE_RULE not in header_text:
        fail("Rewrite/Sources/Header-Rewrite.conf missing Spotify if-none-match header rewrite")
    for marker in SPOTIFY_SCRIPT_MARKERS:
        if marker not in spotify_text:
            fail(f"Scripts/spotify.conf missing {marker}")
    mitm_core_hosts = parse_hosts(mitm_core_text)
    for host in SPOTIFY_MITM_HOSTS:
        if host not in mitm_core_hosts:
            fail(f"Rewrite/Sources/MITM-core.conf missing Spotify MITM hostname: {host}")

    for path in (MODULE, RELEASE):
        text = read_text(path)
        label = path.relative_to(ROOT).as_posix()
        if SPOTIFY_HEADER_REWRITE_RULE not in text:
            fail(f"{label} missing Spotify if-none-match header rewrite")
        for marker in SPOTIFY_SCRIPT_MARKERS:
            if marker not in text:
                fail(f"{label} missing {marker}")
        hosts = parse_hosts(text[text.find("[MITM]"):])
        for host in SPOTIFY_MITM_HOSTS:
            if host not in hosts:
                fail(f"{label} missing Spotify MITM hostname: {host}")


def validate_zhihu_enhance() -> None:
    conf_path = ROOT / "Scripts" / "zhihu-enhance.conf"
    js_path = ROOT / "Scripts" / "zhihu-enhance.js"
    fusion_path = ROOT / "Rewrite" / "Profiles" / "fusion.conf"

    conf = read_text(conf_path)
    js = read_text(js_path)
    fusion = read_text(fusion_path)
    root = read_text(MODULE)

    if "zhihu-enhance" not in conf or "script-path=https://raw.githubusercontent.com/GrandpaNiuu/GrandpaNiu/main/Scripts/zhihu-enhance.js" not in conf:
        fail("Scripts/zhihu-enhance.conf must define zhihu-enhance and its raw script-path")
    if not ZH_FILTER_PATTERN.search(conf):
        fail("Scripts/zhihu-enhance.conf does not appear to target Zhihu ad/feed interfaces")
    if "zhihu_enhance = Scripts/zhihu-enhance.conf" not in fusion:
        fail("fusion.conf must include Scripts/zhihu-enhance.conf")
    if "membership" not in js or "payment" not in js or "login" not in js or "paid_content" not in js:
        fail("zhihu-enhance.js must keep membership/payment/login/paid-content safety boundaries")
    for token in ("vip_status", "is_vip", "paywall"):
        if token in js.lower():
            fail(f"zhihu-enhance.js contains risky entitlement token: {token}")
    if "zhihu-enhance" not in root:
        fail("root module must contain zhihu-enhance after factory build")


def validate_rules() -> None:
    spotify_rules = list(active_lines(read_text(ROOT / "Rules" / "spotify-direct.list")))
    if not spotify_rules:
        fail("Rules/spotify-direct.list is empty")
    for line in spotify_rules:
        if "REJECT" in line.upper():
            fail("Rules/spotify-direct.list must not contain REJECT rules")
    if not any("spotify.com" in line for line in spotify_rules):
        fail("Rules/spotify-direct.list must contain Spotify domains")


def validate_mitm() -> None:
    text = read_text(MODULE)
    mitm_start = text.find("[MITM]")
    if mitm_start < 0:
        fail("[MITM] missing")
    hosts = parse_hosts(text[mitm_start:])
    if not hosts:
        fail("MITM hostname list is empty")
    dupes = sorted({host for host in hosts if hosts.count(host) > 1})
    if dupes:
        fail("duplicate MITM hostnames: " + ", ".join(dupes[:20]))


def validate_fusion_profile() -> None:
    fusion = read_text(ROOT / "Rewrite" / "Profiles" / "fusion.conf")
    required_tokens = (
        "name = fusion",
        "Rules/wechat-ad.list",
        "Rules/aggressive-ad-sources.list",
        "Scripts/app2smile-qqnews-stable-plus.conf",
        "Rewrite/Sources/MITM-core.conf",
        "Rewrite/Sources/MITM-app-clean.conf",
        "Rewrite/Sources/MITM-stable-plus.conf",
        "Rewrite/Sources/MITM-extended.conf",
        "single_public_entry = true",
    )
    for token in required_tokens:
        if token not in fusion:
            fail(f"fusion.conf missing required token: {token}")


def validate_readme_links() -> None:
    text = read_text(README)
    for match in MD_LINK_RE.finditer(text):
        target = match.group(1).strip()
        if not target or target.startswith(("http://", "https://", "#", "mailto:")):
            continue
        path_part = target.split("#", 1)[0]
        if not path_part:
            continue
        if not (ROOT / path_part).exists():
            fail(f"README link target missing: {target}")


def validate_no_tool_traces() -> None:
    for relative in (".claude", "CLAUDE.md"):
        if (ROOT / relative).exists():
            fail(f"tool trace file should not exist: {relative}")
    scan_paths = [README, ROOT / "docs" / "FACTORY_FLOW.md"]
    for path in scan_paths:
        text = read_text(path)
        for token in RISK_TOKENS:
            if token in {".claude", "CLAUDE.md"}:
                continue
            if token in text:
                fail(f"tool trace token found in {path.relative_to(ROOT)}: {token}")


def validate_policy_language() -> None:
    forbidden = ("核心" + "保护对象", "核心" + "专项", "核心" + "链路")
    scan_paths = [
        README,
        ROOT / "docs" / "MODULE_FEATURES.md",
        ROOT / "docs" / "AUTOMATION_POLICY.md",
        ROOT / "docs" / "PROFILE_POLICY.md",
        ROOT / "import.html",
    ]
    for path in scan_paths:
        text = read_text(path)
        for token in forbidden:
            if token in text:
                fail(f"forbidden policy phrase found in {path.relative_to(ROOT)}: {token}")


def validate_governance_files() -> None:
    for relative in REQUIRED_GOVERNANCE_FILES:
        path = ROOT / relative
        if not path.exists():
            fail(f"required governance file missing: {relative}")
    manifest = read_json(ROOT / "backup" / "manifest.json")
    if not isinstance(manifest, list):
        fail("backup/manifest.json must be a list")


def validate_workflows() -> None:
    for relative in REQUIRED_WORKFLOWS:
        path = ROOT / relative
        if not path.exists():
            fail(f"required workflow missing: {relative}")
        text = read_text(path)
        if "contents: write" not in text:
            fail(f"workflow must declare contents: write: {relative}")
        if "concurrency:" not in text:
            fail(f"workflow must declare concurrency: {relative}")

    factory_workflow = read_text(ROOT / ".github" / "workflows" / "module-factory-build.yml")
    daily_workflow = read_text(ROOT / ".github" / "workflows" / "daily-module-update.yml")
    health_workflow = read_text(ROOT / ".github" / "workflows" / "repository-health.yml")
    for name, workflow in (("module-factory-build", factory_workflow), ("daily-module-update", daily_workflow), ("repository-health", health_workflow)):
        if "--profile fusion" not in workflow:
            fail(f"{name} workflow must use the fusion profile by default")

    for token in ("[URL Rewrite]", "[Header Rewrite]", "[Body Rewrite]", "[Map Local]", "zhihu-enhance", "zhihu-enhance.js", "validate_repository.py", "build_release_variants.py"):
        if token not in daily_workflow:
            fail(f"daily-module-update workflow missing validation token: {token}")


def main() -> None:
    validate_root_release()
    validate_single_release_report()
    validate_remote_schema()
    validate_scripts()
    validate_spotify_integration()
    validate_zhihu_enhance()
    validate_rules()
    validate_mitm()
    validate_fusion_profile()
    validate_readme_links()
    validate_no_tool_traces()
    validate_policy_language()
    validate_governance_files()
    validate_workflows()
    print("Repository validation passed.")


if __name__ == "__main__":
    main()
