#!/usr/bin/env python3
"""Unified repository validator for the source-driven module factory."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parents[1]
MODULE = ROOT / "Ronghemokuai.sgmodule"
RELEASE = ROOT / "Release" / "Ronghemokuai.sgmodule"
SOURCES_JSON = ROOT / "Rewrite" / "Remotes" / "sources.json"
CANDIDATES_JSON = ROOT / "Rewrite" / "Remotes" / "candidates.json"
README = ROOT / "README.md"
EXPECTED_UPDATE_URL = "#!update-url=https://grandpaniuu.github.io/GrandpaNiu/Ronghemokuai.sgmodule"
REQUIRED_MARKERS = (
    "[Rule]",
    "[URL Rewrite]",
    "[Header Rewrite]",
    "[Body Rewrite]",
    "[Map Local]",
    "[Script]",
    "[MITM]",
    "spotify-json",
    "spotify-proto",
    "youtube.response",
    "zhihu-enhance",
    EXPECTED_UPDATE_URL,
)
ALLOWED_REMOTE_TYPES = {"RULE-SET", "DOMAIN-SET"}
ALLOWED_POLICIES = {"REJECT", "REJECT-DROP", "DIRECT"}
BLOCKED_URL_TOKENS = ("ghproxy", "mirror", "tinyurl", "bit.ly", "t.co/", "shorturl")
RISK_TOKENS = (
    "GPT",
    "ChatGPT",
    "OpenAI",
    "generated by AI",
    ".claude",
    "CLAUDE.md",
)
SCRIPT_NAME_RE = re.compile(r"^\s*([^#\s][^=]+?)\s*=")
HOSTNAME_RE = re.compile(r"^\s*hostname\s*=\s*(.+)$")
MD_LINK_RE = re.compile(r"\[[^\]]+\]\(([^)]+)\)")
ZH_FILTER_PATTERN = re.compile(r"(topstory|moments|feed|questions|answers|search|commercial|market|ad|recommend)", re.I)


def fail(message: str) -> None:
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(1)


def read_text(path: Path) -> str:
    if not path.exists():
        fail(f"missing file: {path.relative_to(ROOT)}")
    return path.read_text(encoding="utf-8", errors="replace")


def read_json(path: Path) -> dict:
    try:
        return json.loads(read_text(path))
    except json.JSONDecodeError as exc:
        fail(f"invalid JSON in {path.relative_to(ROOT)}: {exc}")


def active_lines(text: str) -> Iterable[str]:
    for line in text.splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            yield stripped


def validate_root_release() -> None:
    root_text = read_text(MODULE)
    release_text = read_text(RELEASE)
    if root_text != release_text:
        fail("Ronghemokuai.sgmodule and Release/Ronghemokuai.sgmodule differ")
    for marker in REQUIRED_MARKERS:
        if marker not in root_text:
            fail(f"required marker missing from root module: {marker}")


def validate_remote_schema() -> None:
    data = read_json(SOURCES_JSON)
    urls: set[str] = set()
    for index, item in enumerate(data.get("rule_sets", []), 1):
        for key in ("name", "type", "url", "policy", "enabled", "protected", "purpose"):
            if key not in item:
                fail(f"sources.json rule_sets[{index}] missing {key}")
        if item["type"] not in ALLOWED_REMOTE_TYPES:
            fail(f"sources.json rule_sets[{index}] invalid type: {item['type']}")
        if item["policy"] not in ALLOWED_POLICIES:
            fail(f"sources.json rule_sets[{index}] invalid policy: {item['policy']}")
        url = str(item["url"])
        if not url.startswith("https://"):
            fail(f"sources.json rule_sets[{index}] must use https: {url}")
        if any(token in url.lower() for token in BLOCKED_URL_TOKENS):
            fail(f"sources.json rule_sets[{index}] uses blocked host/token: {url}")
        if url in urls:
            fail(f"duplicate remote source url in sources.json: {url}")
        urls.add(url)

    candidates = read_json(CANDIDATES_JSON)
    if candidates.get("policy", {}).get("search_web") is not False:
        fail("candidates.json policy.search_web must stay false")
    trusted = candidates.get("trusted_repositories", [])
    if not isinstance(trusted, list) or not trusted:
        fail("candidates.json must define trusted_repositories")
    for index, item in enumerate(candidates.get("candidates", []), 1):
        for key in ("name", "kind", "url", "purpose"):
            if key not in item:
                fail(f"candidates.json candidates[{index}] missing {key}")
        url = str(item["url"])
        if not url.startswith("https://"):
            fail(f"candidates.json candidates[{index}] must use https: {url}")
        if any(token in url.lower() for token in BLOCKED_URL_TOKENS):
            fail(f"candidates.json candidates[{index}] uses blocked host/token: {url}")


def validate_scripts() -> None:
    spotify_text = read_text(ROOT / "Scripts" / "spotify.conf")
    youtube_text = read_text(ROOT / "Scripts" / "youtube.conf")
    app_text = read_text(ROOT / "Scripts" / "app-clean.conf")

    for token in ("tieba", "qq-news", "vgtime"):
        if token in spotify_text.lower():
            fail(f"Scripts/spotify.conf contains non-Spotify token: {token}")
    for token in ("tieba", "qq-news", "vgtime", "spotify-proto", "spotify-json"):
        if token in youtube_text.lower() and token not in {"youtube"}:
            fail(f"Scripts/youtube.conf contains wrong token: {token}")
    if "spotify-json" not in spotify_text or "spotify-proto" not in spotify_text:
        fail("Scripts/spotify.conf must contain spotify-json and spotify-proto")
    if "youtube.response" not in youtube_text:
        fail("Scripts/youtube.conf must contain youtube.response")
    if not any(token in app_text.lower() for token in ("tieba", "qq-news", "vgtime", "fmz200", "zirawell", "wool_scripts", "app2smile")):
        fail("Scripts/app-clean.conf does not appear to contain app cleanup scripts")

    names: set[str] = set()
    for path in (ROOT / "Scripts").glob("*.conf"):
        for line in active_lines(read_text(path)):
            match = SCRIPT_NAME_RE.match(line)
            if not match:
                continue
            name = match.group(1).strip()
            if name in names:
                fail(f"duplicate script name: {name}")
            names.add(name)


def validate_zhihu_enhance() -> None:
    conf_path = ROOT / "Scripts" / "zhihu-enhance.conf"
    js_path = ROOT / "Scripts" / "zhihu-enhance.js"
    stable_path = ROOT / "Rewrite" / "Profiles" / "stable.conf"
    lite_path = ROOT / "Rewrite" / "Profiles" / "lite.conf"

    conf = read_text(conf_path)
    js = read_text(js_path)
    stable = read_text(stable_path)
    lite = read_text(lite_path)
    root = read_text(MODULE)

    if "zhihu-enhance" not in conf or "script-path=https://raw.githubusercontent.com/GrandpaNiuu/GrandpaNiu/main/Scripts/zhihu-enhance.js" not in conf:
        fail("Scripts/zhihu-enhance.conf must define zhihu-enhance and its raw script-path")
    if not ZH_FILTER_PATTERN.search(conf):
        fail("Scripts/zhihu-enhance.conf does not appear to target Zhihu ad/feed interfaces")
    if "zhihu_enhance = Scripts/zhihu-enhance.conf" not in stable:
        fail("stable.conf must include Scripts/zhihu-enhance.conf")
    if "zhihu_enhance = Scripts/zhihu-enhance.conf" not in lite:
        fail("lite.conf must include Scripts/zhihu-enhance.conf")
    if "membership" not in js or "payment" not in js or "login" not in js or "paid_content" not in js:
        fail("zhihu-enhance.js must keep membership/payment/login/paid-content safety boundaries")
    for token in ("vip_status", "is_vip", "unlock", "paywall", "cookie", "token"):
        if token in js.lower():
            fail(f"zhihu-enhance.js contains risky account or entitlement token: {token}")
    if "zhihu-enhance" not in root:
        fail("root module must contain zhihu-enhance after factory build")


def validate_rules() -> None:
    spotify_rules = list(active_lines(read_text(ROOT / "Rules" / "spotify-direct.list")))
    if not spotify_rules:
        fail("Rules/spotify-direct.list is empty")
    for line in spotify_rules:
        if "REJECT" in line.upper():
            fail("Rules/spotify-direct.list must not contain REJECT rules")
    if not any("spotify.com" in line for line in spotify_rules):
        fail("Rules/spotify-direct.list must contain Spotify domains")


def validate_mitm() -> None:
    text = read_text(MODULE)
    mitm_start = text.find("[MITM]")
    if mitm_start < 0:
        fail("[MITM] missing")
    tail = text[mitm_start:]
    hosts: list[str] = []
    for line in tail.splitlines():
        match = HOSTNAME_RE.match(line)
        if not match:
            continue
        for host in match.group(1).split(","):
            clean = host.strip()
            if clean and clean != "%APPEND%":
                hosts.append(clean)
    if not hosts:
        fail("MITM hostname list is empty")
    dupes = sorted({host for host in hosts if hosts.count(host) > 1})
    if dupes:
        fail("duplicate MITM hostnames: " + ", ".join(dupes[:20]))


def validate_readme_links() -> None:
    text = read_text(README)
    for match in MD_LINK_RE.finditer(text):
        target = match.group(1).strip()
        if not target or target.startswith(("http://", "https://", "#", "mailto:")):
            continue
        path_part = target.split("#", 1)[0]
        if not path_part:
            continue
        if not (ROOT / path_part).exists():
            fail(f"README link target missing: {target}")


def validate_no_tool_traces() -> None:
    for relative in (".claude", "CLAUDE.md"):
        if (ROOT / relative).exists():
            fail(f"tool trace file should not exist: {relative}")
    scan_paths = [README, ROOT / "docs" / "FACTORY_FLOW.md"]
    for path in scan_paths:
        text = read_text(path)
        for token in RISK_TOKENS:
            if token in {".claude", "CLAUDE.md"}:
                continue
            if token in text:
                fail(f"tool trace token found in {path.relative_to(ROOT)}: {token}")


def main() -> None:
    validate_root_release()
    validate_remote_schema()
    validate_scripts()
    validate_zhihu_enhance()
    validate_rules()
    validate_mitm()
    validate_readme_links()
    validate_no_tool_traces()
    print("Repository validation passed.")


if __name__ == "__main__":
    main()
